"use client";
import { useMemo, useState } from "react";
import type { DepartmentRepository } from "../repositories/contracts/department-repository.ts";
import type { PositionRepository } from "../repositories/contracts/position-repository.ts";
import type { DepartmentAlias, DepartmentNode, OfficialPosition, PositionFamily, PositionSourceLabel } from "../repositories/contracts/organization-models.ts";
import { filterMappingItems,getMappingSummary,selectHighConfidenceMappings,type MappingFilters,type MappingItem,type MappingItemStatus } from "../services/mapping-workflow.ts";
import { createdDepartmentAliasResolution } from "./department-alias-resolution.ts";

type Props={tenantId:string;propertyId:string;aliases:DepartmentAlias[];positionLabels:PositionSourceLabel[];tree:DepartmentNode[];positions:OfficialPosition[];families:PositionFamily[];departmentRepository:DepartmentRepository;positionRepository:PositionRepository;complete:boolean;blocked:boolean;onAliases:(items:DepartmentAlias[])=>void;onPositions:(items:PositionSourceLabel[])=>void;onTree:(items:DepartmentNode[])=>void;onOfficialPositions:(items:OfficialPosition[])=>void;onFamilies:(items:PositionFamily[])=>void;onConfirm:()=>Promise<void>;notify:(message:string)=>void};
type DialogAction="department"|"create-root"|"create-child"|"operational-unit"|"merge"|"position"|"create-position"|"family"|"external";
const pageSize=8;
export function MappingSetupStep(props:Props){
  const {aliases,positionLabels,tree,positions,families}=props;
  const [filters,setFilters]=useState<MappingFilters>({query:"",type:"all",status:"all",unresolvedOnly:true,sortBy:"affectedRows"});const [selected,setSelected]=useState(new Set<string>());const [page,setPage]=useState(1);const [ignoreConfirm,setIgnoreConfirm]=useState(false);const[dialog,setDialog]=useState<{item:MappingItem;action:DialogAction}|null>(null);const[targetId,setTargetId]=useState("");const[parentId,setParentId]=useState("");const[nameZh,setNameZh]=useState("");const[nameEn,setNameEn]=useState("");const[code,setCode]=useState("");const[familyId,setFamilyId]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");
  const items=useMemo(()=>toItems({aliases,positionLabels,tree,positions,families}),[aliases,positionLabels,tree,positions,families]);const summary=getMappingSummary(items);const filtered=filterMappingItems(items,filters);const pages=Math.max(1,Math.ceil(filtered.length/pageSize));const visible=filtered.slice((Math.min(page,pages)-1)*pageSize,Math.min(page,pages)*pageSize);
  const mutate=async(ids:readonly string[],action:"accept"|"defer"|"ignore")=>{let affected=0;for(const id of ids){const item=items.find(entry=>entry.id===id);if(!item||(action==="accept"&&item.blocked))continue;affected+=item.affectedRows;if(item.type==="department"){const source=props.aliases.find(entry=>entry.id===id)!;await props.departmentRepository.approveMapping({aliasId:id,action:action==="accept"?"department":action,targetDepartmentId:action==="accept"?source.suggestedTargetId??undefined:undefined});}else{const source=props.positionLabels.find(entry=>entry.id===id)!;await props.positionRepository.approvePositionMapping({sourceLabelId:id,action:action==="accept"?source.suggestedPositionId?"position":"family":action,targetPositionId:source.suggestedPositionId??undefined,targetPositionFamilyId:source.suggestedFamilyId??undefined});}}
    props.onAliases(await props.departmentRepository.listAliases(props.propertyId));props.onPositions(await props.positionRepository.listSourceLabels(props.propertyId));setSelected(new Set());setIgnoreConfirm(false);props.notify(`${ids.length} 个来源标签已处理，影响 ${affected} 条合成记录`)};
  const openDialog=(item:MappingItem,action:DialogAction)=>{setDialog({item,action});setTargetId("");setParentId("");setNameZh(item.sourceLabel);setNameEn(item.sourceLabel);setCode(slug(item.sourceLabel));setFamilyId("");setError("")};
  const confirmDialog=async()=>{if(!dialog)return;setBusy(true);setError("");try{const item=dialog.item;
    if(item.type==="department"){
      if(dialog.action==="create-root"||dialog.action==="create-child"){
        if(!nameZh.trim())throw new Error("请输入正式部门中文名称");
        await props.departmentRepository.approveMapping(createdDepartmentAliasResolution({aliasId:item.id,action:dialog.action,parentId:parentId||null,code:code||slug(nameEn||nameZh),nameZh:nameZh.trim(),nameEn:nameEn.trim(),sortOrder:(tree.length+1)*10}));
        props.onTree(await props.departmentRepository.listTree(props.propertyId));
      }else if(dialog.action==="operational-unit"){
        if(!targetId)throw new Error("请选择运营单元所属的正式部门");const unit=await props.departmentRepository.createOperationalUnit({tenantId:props.tenantId,propertyId:props.propertyId,departmentId:targetId,parentOperationalUnitId:null,unitType:"other",code:code||slug(nameEn||nameZh),nameZh:nameZh.trim(),nameEn:nameEn.trim(),sortOrder:10});await props.departmentRepository.approveMapping({aliasId:item.id,action:"operational_unit",operationalUnitId:unit.id});
      }else{
        if(!targetId)throw new Error("请选择正式部门");const resolution=dialog.action==="merge"?"merged":"mapped";await props.departmentRepository.approveMapping({aliasId:item.id,action:dialog.action==="merge"?"merge":"department",targetDepartmentId:targetId,resolutionType:resolution});
      }
    }else{
      let positionId=targetId;
      if(dialog.action==="create-position"){if(!nameZh.trim()||!parentId)throw new Error("请输入正式职位名称并选择适用部门");const saved=await props.positionRepository.savePosition({tenantId:props.tenantId,propertyId:props.propertyId,positionFamilyId:familyId||null,code:code||slug(nameEn||nameZh),nameZh:nameZh.trim(),nameEn:nameEn.trim()||null,gradeOrBand:null,isActive:true});await props.positionRepository.assignPositionToDepartments(saved.id,[parentId]);positionId=saved.id;props.onOfficialPositions(await props.positionRepository.listPositions(props.propertyId));}
      if(dialog.action==="family"){if(!familyId)throw new Error("请选择职位族");await props.positionRepository.approvePositionMapping({sourceLabelId:item.id,action:"family",targetPositionFamilyId:familyId});}
      else if(dialog.action==="external"){if(!code.trim()||!nameEn.trim())throw new Error("请输入外部角色代码和名称");await props.positionRepository.approvePositionMapping({sourceLabelId:item.id,action:"external",externalRoleCode:code.trim(),externalRoleName:nameEn.trim()});}
      else{if(!positionId)throw new Error("请选择正式职位");await props.positionRepository.approvePositionMapping({sourceLabelId:item.id,action:"position",targetPositionId:positionId,targetPositionFamilyId:(props.positions.find(value=>value.id===positionId)?.positionFamilyId??familyId)||undefined});}
    }
    props.onAliases(await props.departmentRepository.listAliases(props.propertyId));props.onPositions(await props.positionRepository.listSourceLabels(props.propertyId));setDialog(null);props.notify(`“${item.sourceLabel}”的认领结果已保存`);
  }catch(reason){setError(reason instanceof Error?reason.message:"无法保存认领结果")}finally{setBusy(false)}};
  const selectedIds=[...selected];const highConfidence=selectHighConfidenceMappings(items,selected,90);
  const statusLabel=(status:MappingItemStatus)=>({pending:"待处理",mapped:"已映射",ignored:"已忽略",deferred:"已延期",blocked:"阻塞",family_only:"职位族",external_only:"外部角色",merged:"已合并"}[status]);
  return <section className="wizard-card mapping-workspace"><header className="wizard-intro"><h3>按优先级认领来源标签</h3><p>搜索、筛选、分组和批量动作可处理大量来源标签；系统不会批量新建正式部门或职位。</p></header>
    <div className="mapping-summary"><div><span>认领进度</span><strong>{summary.progressPercent}%</strong><small>{summary.resolved} / {summary.total} 已处理</small></div><div><span>未解决</span><strong>{summary.unresolved}</strong><small>{summary.blocked} 个阻塞</small></div><div><span>受影响记录</span><strong>{summary.affectedRows}</strong><small>执行前始终显示影响</small></div><div><span>当前筛选结果</span><strong>{filtered.length}</strong><small>每页 {pageSize} 项</small></div></div>
    <div className="mapping-filters"><label>搜索来源标签<input value={filters.query} placeholder="关键词、建议或目标" onChange={event=>{setFilters({...filters,query:event.target.value});setPage(1)}}/></label><label>类型<select value={filters.type} onChange={event=>{setFilters({...filters,type:event.target.value as MappingFilters["type"]});setPage(1)}}><option value="all">全部类型</option><option value="department">部门</option><option value="position">职位</option></select></label><label>状态<select value={filters.status} onChange={event=>{setFilters({...filters,status:event.target.value as MappingFilters["status"]});setPage(1)}}><option value="all">全部状态</option>{["pending","mapped","ignored","deferred","blocked"].map(value=><option key={value} value={value}>{statusLabel(value as MappingItemStatus)}</option>)}</select></label><label>排序<select value={filters.sortBy} onChange={event=>setFilters({...filters,sortBy:event.target.value as MappingFilters["sortBy"]})}><option value="affectedRows">影响人数</option><option value="confidence">置信度</option><option value="sourceLabel">来源标签</option><option value="status">状态</option></select></label><label className="mapping-toggle"><input type="checkbox" checked={filters.unresolvedOnly} onChange={event=>{setFilters({...filters,unresolvedOnly:event.target.checked});setPage(1)}}/><span>仅看未处理</span></label></div>
    <div className="mapping-groups" aria-label="映射状态分组"><span>待处理 {summary.pending}</span><span>已映射 {summary.resolved}</span><span>已忽略 {summary.ignored}</span><span>已延期 {summary.deferred}</span><span className={summary.blocked?"risk":""}>阻塞 {summary.blocked}</span></div>
    <div className="mapping-batch"><span>已选择 <strong>{selected.size}</strong> 项 · {items.filter(item=>selected.has(item.id)).reduce((sum,item)=>sum+item.affectedRows,0)} 条受影响记录</span><button disabled={!highConfidence.length} onClick={()=>void mutate(highConfidence,"accept")}>批量接受高置信度建议</button><button disabled={!selected.size} onClick={()=>void mutate(selectedIds,"defer")}>批量延期</button><button disabled={!selected.size} className="risk" onClick={()=>setIgnoreConfirm(true)}>批量忽略</button><button onClick={()=>props.notify("已批准的映射已保存，后续导入将自动复用")}>批量保存已批准映射</button></div>
    {ignoreConfirm&&<div className="mapping-confirm" role="dialog" aria-label="确认批量忽略"><strong>确认忽略 {selected.size} 个来源标签？</strong><p>受影响记录不会静默进入员工导入；决定会保留审计记录。</p><button onClick={()=>setIgnoreConfirm(false)}>取消</button><button className="risk" onClick={()=>void mutate(selectedIds,"ignore")}>确认忽略</button></div>}
    <div className="mapping-list">{visible.map(item=><article key={item.id} className={item.blocked?"blocked":""}><label><input type="checkbox" checked={selected.has(item.id)} disabled={item.blocked} onChange={event=>{const next=new Set(selected);if(event.target.checked)next.add(item.id);else next.delete(item.id);setSelected(next)}}/><span className={`mapping-status ${item.status}`}>{statusLabel(item.status)}</span></label><div><div className="mapping-title"><span>{item.type==="department"?"部门标签":"职位标签"}</span><strong>{item.sourceLabel}</strong><small>{item.sourceSheet} · {item.affectedRows} 条受影响记录</small></div><dl><div><dt>建议目标</dt><dd>{item.suggestedTarget??"无自动建议"}</dd></div><div><dt>置信度</dt><dd>{item.confidence}%</dd></div><div><dt>建议理由</dt><dd>{item.suggestionReason}</dd></div><div><dt>当前目标</dt><dd>{item.targetLabel??"尚未选择"}</dd></div></dl><div className="mapping-actions">{item.type==="department"?<><button onClick={()=>openDialog(item,"department")}>选择现有部门</button><button onClick={()=>openDialog(item,"create-root")}>创建一级部门</button><button onClick={()=>openDialog(item,"create-child")}>创建下级部门</button><button onClick={()=>openDialog(item,"operational-unit")}>分类为运营单元</button><button onClick={()=>openDialog(item,"department")}>保存别名</button><button onClick={()=>openDialog(item,"merge")}>合并</button></>:<><button onClick={()=>openDialog(item,"position")}>选择正式职位</button><button onClick={()=>openDialog(item,"create-position")}>创建正式职位</button><button onClick={()=>openDialog(item,"family")}>映射到职位族</button><button onClick={()=>openDialog(item,"external")}>仅作为外部 LMS 角色</button></>}<button onClick={()=>void mutate([item.id],"defer")}>延期</button><button onClick={()=>{setSelected(new Set([item.id]));setIgnoreConfirm(true)}}>忽略</button></div></div></article>)}</div>
    {dialog&&<div className="mapping-item-dialog" role="dialog" aria-label="来源标签认领"><header><div><span>{dialog.item.type==="department"?"部门来源标签":"职位来源标签"}</span><strong>{dialog.item.sourceLabel}</strong><small>{dialog.item.affectedRows} 条来源记录受影响</small></div><button onClick={()=>setDialog(null)}>关闭</button></header><div className="mapping-dialog-form">
      {dialog.item.type==="department"&&["department","merge"].includes(dialog.action)&&<label>{dialog.action==="merge"?"合并到正式部门":"选择正式部门"}<select value={targetId} onChange={event=>setTargetId(event.target.value)}><option value="">请选择</option>{tree.filter(item=>item.isActive).map(item=><option value={item.id} key={item.id}>{item.pathIds.map(id=>tree.find(node=>node.id===id)?.nameZh).filter(Boolean).join(" / ")}</option>)}</select></label>}
      {dialog.item.type==="department"&&["create-root","create-child","operational-unit"].includes(dialog.action)&&<><label>中文名称<input value={nameZh} onChange={event=>setNameZh(event.target.value)}/></label><label>英文名称<input value={nameEn} onChange={event=>setNameEn(event.target.value)}/></label><label>业务代码<input value={code} onChange={event=>setCode(event.target.value)}/></label>{dialog.action==="create-child"&&<label>选择上级部门<select value={parentId} onChange={event=>setParentId(event.target.value)}><option value="">请选择</option>{tree.filter(item=>item.isActive).map(item=><option value={item.id} key={item.id}>{item.nameZh}</option>)}</select></label>}{dialog.action==="operational-unit"&&<label>所属正式部门<select value={targetId} onChange={event=>setTargetId(event.target.value)}><option value="">请选择</option>{tree.filter(item=>item.isActive).map(item=><option value={item.id} key={item.id}>{item.nameZh}</option>)}</select></label>}</>}
      {dialog.item.type==="position"&&dialog.action==="position"&&<label>选择正式职位<select value={targetId} onChange={event=>setTargetId(event.target.value)}><option value="">请选择</option>{positions.filter(item=>item.isActive).map(item=><option value={item.id} key={item.id}>{item.nameZh}</option>)}</select></label>}
      {dialog.item.type==="position"&&dialog.action==="create-position"&&<><label>中文名称<input value={nameZh} onChange={event=>setNameZh(event.target.value)}/></label><label>英文名称<input value={nameEn} onChange={event=>setNameEn(event.target.value)}/></label><label>职位代码<input value={code} onChange={event=>setCode(event.target.value)}/></label><label>职位族<select value={familyId} onChange={event=>setFamilyId(event.target.value)}><option value="">暂不归类</option>{families.filter(item=>item.isActive).map(item=><option value={item.id} key={item.id}>{item.nameZh}</option>)}</select></label><label>适用部门<select value={parentId} onChange={event=>setParentId(event.target.value)}><option value="">请选择</option>{tree.filter(item=>item.isActive).map(item=><option value={item.id} key={item.id}>{item.nameZh}</option>)}</select></label></>}
      {dialog.item.type==="position"&&dialog.action==="family"&&<label>选择职位族<select value={familyId} onChange={event=>setFamilyId(event.target.value)}><option value="">请选择</option>{families.filter(item=>item.isActive).map(item=><option value={item.id} key={item.id}>{item.nameZh}</option>)}</select></label>}
      {dialog.item.type==="position"&&dialog.action==="external"&&<><label>外部角色代码<input value={code} onChange={event=>setCode(event.target.value)}/></label><label>外部角色名称<input value={nameEn} onChange={event=>setNameEn(event.target.value)}/></label></>}
    </div>{error&&<div className="wizard-error" role="alert">{error}</div>}<footer><button onClick={()=>setDialog(null)}>取消</button><button className="wizard-primary" disabled={busy} onClick={()=>void confirmDialog()}>{busy?"保存中…":"确认并保存映射"}</button></footer></div>}
    <div className="mapping-pagination"><button disabled={page<=1} onClick={()=>setPage(value=>Math.max(1,value-1))}>上一页</button><span>第 {Math.min(page,pages)} / {pages} 页</span><button disabled={page>=pages} onClick={()=>setPage(value=>Math.min(pages,value+1))}>下一页</button></div>
    <footer><span className={`wizard-validation ${props.complete?"good":""}`}>{props.blocked?`! 仍有 ${summary.unresolved} 个标签待处理，保存后可继续回来完成`:"✓ 所有必要标签已处理"}</span><button className="wizard-primary" disabled={props.blocked} onClick={()=>void props.onConfirm()}>确认映射并继续</button></footer>
  </section>;
}

function slug(value:string){return value.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||`source-${Date.now()}`}

function toItems(props:Pick<Props,"aliases"|"positionLabels"|"tree"|"positions"|"families">):MappingItem[]{
  const path=(id:string|null)=>{const node=props.tree.find(item=>item.id===id);return node?.pathIds.map(pathId=>props.tree.find(item=>item.id===pathId)?.nameZh).filter(Boolean).join(" / ")??null};
  const departmentItems:MappingItem[]=props.aliases.map(item=>({id:item.id,type:"department",sourceLabel:item.sourceValue,affectedRows:item.syntheticEmployeeCount,sourceSheet:item.sourceSheet,suggestedTarget:item.suggestionLabel,confidence:item.confidence,suggestionReason:item.suggestionReason,targetLabel:path(item.targetDepartmentId),status:departmentStatus(item.resolutionType,Boolean(item.suggestedTargetId)),blocked:item.resolutionType==="deferred"&&!item.suggestedTargetId,batchEligible:Boolean(item.suggestedTargetId)&&!item.suggestionLabel.includes("运营单元")}));
  const positionItems:MappingItem[]=props.positionLabels.map(item=>({id:item.id,type:"position",sourceLabel:item.sourceValue,affectedRows:item.syntheticEmployeeCount,sourceSheet:item.sourceSheet,suggestedTarget:props.positions.find(position=>position.id===item.suggestedPositionId)?.nameZh??props.families.find(family=>family.id===item.suggestedFamilyId)?.nameZh??null,confidence:item.confidence,suggestionReason:item.suggestionReason,targetLabel:props.positions.find(position=>position.id===item.targetPositionId)?.nameZh??props.families.find(family=>family.id===item.targetPositionFamilyId)?.nameZh??null,status:item.resolutionStatus==="deferred"?(item.suggestedPositionId||item.suggestedFamilyId?"pending":"blocked"):item.resolutionStatus,blocked:item.resolutionStatus==="deferred"&&!item.suggestedPositionId&&!item.suggestedFamilyId,batchEligible:Boolean(item.suggestedPositionId)}));
  return [...departmentItems,...positionItems];
}

function departmentStatus(status:DepartmentAlias["resolutionType"],hasSuggestion:boolean):MappingItemStatus{
  if(status==="deferred")return hasSuggestion?"pending":"blocked";
  if(status==="created_top_level"||status==="created_child")return "mapped";
  return status;
}
