"use client";
import { useMemo, useState } from "react";
import type { DepartmentRepository } from "../repositories/contracts/department-repository.ts";
import type { PositionRepository } from "../repositories/contracts/position-repository.ts";
import type { DepartmentAlias, DepartmentNode, OfficialPosition, PositionFamily, PositionSourceLabel } from "../repositories/contracts/organization-models.ts";
import { filterMappingItems,getMappingSummary,selectHighConfidenceMappings,type MappingFilters,type MappingItem,type MappingItemStatus } from "../services/mapping-workflow.ts";

type Props={propertyId:string;aliases:DepartmentAlias[];positionLabels:PositionSourceLabel[];tree:DepartmentNode[];positions:OfficialPosition[];families:PositionFamily[];departmentRepository:DepartmentRepository;positionRepository:PositionRepository;complete:boolean;blocked:boolean;onAliases:(items:DepartmentAlias[])=>void;onPositions:(items:PositionSourceLabel[])=>void;onConfirm:()=>Promise<void>;notify:(message:string)=>void};
const pageSize=8;
export function MappingSetupStep(props:Props){
  const {aliases,positionLabels,tree,positions,families}=props;
  const [filters,setFilters]=useState<MappingFilters>({query:"",type:"all",status:"all",unresolvedOnly:true,sortBy:"affectedRows"});const [selected,setSelected]=useState(new Set<string>());const [page,setPage]=useState(1);const [ignoreConfirm,setIgnoreConfirm]=useState(false);
  const items=useMemo(()=>toItems({aliases,positionLabels,tree,positions,families}),[aliases,positionLabels,tree,positions,families]);const summary=getMappingSummary(items);const filtered=filterMappingItems(items,filters);const pages=Math.max(1,Math.ceil(filtered.length/pageSize));const visible=filtered.slice((Math.min(page,pages)-1)*pageSize,Math.min(page,pages)*pageSize);
  const mutate=async(ids:readonly string[],action:"accept"|"defer"|"ignore")=>{let affected=0;for(const id of ids){const item=items.find(entry=>entry.id===id);if(!item||item.blocked)continue;affected+=item.affectedRows;if(item.type==="department"){const source=props.aliases.find(entry=>entry.id===id)!;await props.departmentRepository.approveMapping({aliasId:id,action:action==="accept"?"department":action,targetDepartmentId:action==="accept"?source.suggestedTargetId??undefined:undefined});}else{const source=props.positionLabels.find(entry=>entry.id===id)!;await props.positionRepository.approvePositionMapping({sourceLabelId:id,action:action==="accept"?source.suggestedPositionId?"position":"family":action,targetPositionId:source.suggestedPositionId??undefined,targetPositionFamilyId:source.suggestedFamilyId??undefined});}}
    props.onAliases(await props.departmentRepository.listAliases(props.propertyId));props.onPositions(await props.positionRepository.listSourceLabels(props.propertyId));setSelected(new Set());setIgnoreConfirm(false);props.notify(`${ids.length} 个来源标签已处理，影响 ${affected} 条合成记录`)};
  const selectedIds=[...selected];const highConfidence=selectHighConfidenceMappings(items,selected,90);
  const statusLabel=(status:MappingItemStatus)=>({pending:"待处理",mapped:"已映射",ignored:"已忽略",deferred:"已延期",blocked:"阻塞",family_only:"职位族",external_only:"外部角色",merged:"已合并"}[status]);
  return <section className="wizard-card mapping-workspace"><header className="wizard-intro"><h3>按优先级认领来源标签</h3><p>搜索、筛选、分组和批量动作可处理大量来源标签；系统不会批量新建正式部门或职位。</p></header>
    <div className="mapping-summary"><div><span>认领进度</span><strong>{summary.progressPercent}%</strong><small>{summary.resolved} / {summary.total} 已处理</small></div><div><span>未解决</span><strong>{summary.unresolved}</strong><small>{summary.blocked} 个阻塞</small></div><div><span>受影响记录</span><strong>{summary.affectedRows}</strong><small>执行前始终显示影响</small></div><div><span>当前筛选结果</span><strong>{filtered.length}</strong><small>每页 {pageSize} 项</small></div></div>
    <div className="mapping-filters"><label>搜索来源标签<input value={filters.query} placeholder="关键词、建议或目标" onChange={event=>{setFilters({...filters,query:event.target.value});setPage(1)}}/></label><label>类型<select value={filters.type} onChange={event=>{setFilters({...filters,type:event.target.value as MappingFilters["type"]});setPage(1)}}><option value="all">全部类型</option><option value="department">部门</option><option value="position">职位</option></select></label><label>状态<select value={filters.status} onChange={event=>{setFilters({...filters,status:event.target.value as MappingFilters["status"]});setPage(1)}}><option value="all">全部状态</option>{["pending","mapped","ignored","deferred","blocked"].map(value=><option key={value} value={value}>{statusLabel(value as MappingItemStatus)}</option>)}</select></label><label>排序<select value={filters.sortBy} onChange={event=>setFilters({...filters,sortBy:event.target.value as MappingFilters["sortBy"]})}><option value="affectedRows">影响人数</option><option value="confidence">置信度</option><option value="sourceLabel">来源标签</option><option value="status">状态</option></select></label><label className="mapping-toggle"><input type="checkbox" checked={filters.unresolvedOnly} onChange={event=>{setFilters({...filters,unresolvedOnly:event.target.checked});setPage(1)}}/><span>仅看未处理</span></label></div>
    <div className="mapping-groups" aria-label="映射状态分组"><span>待处理 {summary.pending}</span><span>已映射 {summary.resolved}</span><span>已忽略 {summary.ignored}</span><span>已延期 {summary.deferred}</span><span className={summary.blocked?"risk":""}>阻塞 {summary.blocked}</span></div>
    <div className="mapping-batch"><span>已选择 <strong>{selected.size}</strong> 项 · {items.filter(item=>selected.has(item.id)).reduce((sum,item)=>sum+item.affectedRows,0)} 条受影响记录</span><button disabled={!highConfidence.length} onClick={()=>void mutate(highConfidence,"accept")}>批量接受高置信度建议</button><button disabled={!selected.size} onClick={()=>void mutate(selectedIds,"defer")}>批量延期</button><button disabled={!selected.size} className="risk" onClick={()=>setIgnoreConfirm(true)}>批量忽略</button><button onClick={()=>props.notify("已批准的映射已保存，后续导入将自动复用")}>批量保存已批准映射</button></div>
    {ignoreConfirm&&<div className="mapping-confirm" role="dialog" aria-label="确认批量忽略"><strong>确认忽略 {selected.size} 个来源标签？</strong><p>受影响记录不会静默进入员工导入；决定会保留审计记录。</p><button onClick={()=>setIgnoreConfirm(false)}>取消</button><button className="risk" onClick={()=>void mutate(selectedIds,"ignore")}>确认忽略</button></div>}
    <div className="mapping-list">{visible.map(item=><article key={item.id} className={item.blocked?"blocked":""}><label><input type="checkbox" checked={selected.has(item.id)} disabled={item.blocked} onChange={event=>{const next=new Set(selected);if(event.target.checked)next.add(item.id);else next.delete(item.id);setSelected(next)}}/><span className={`mapping-status ${item.status}`}>{statusLabel(item.status)}</span></label><div><div className="mapping-title"><span>{item.type==="department"?"部门标签":"职位标签"}</span><strong>{item.sourceLabel}</strong><small>{item.sourceSheet} · {item.affectedRows} 条受影响记录</small></div><dl><div><dt>建议目标</dt><dd>{item.suggestedTarget??"无自动建议"}</dd></div><div><dt>置信度</dt><dd>{item.confidence}%</dd></div><div><dt>建议理由</dt><dd>{item.suggestionReason}</dd></div><div><dt>当前目标</dt><dd>{item.targetLabel??"尚未选择"}</dd></div></dl><div className="mapping-actions">{item.type==="department"?<><button onClick={()=>void mutate([item.id],"accept")}>映射到现有部门</button><button onClick={()=>props.notify("新增一级部门需要逐项确认")}>创建一级部门</button><button onClick={()=>props.notify("创建下级部门需要选择正式上级")}>创建下级部门</button><button onClick={()=>props.notify("运营单元分类面板已打开")}>分类为运营单元</button><button onClick={()=>props.notify("别名将在映射确认后保存")}>保存别名</button><button onClick={()=>props.notify("合并来源标签面板已打开")}>合并</button></>:<><button onClick={()=>void mutate([item.id],"accept")}>映射到正式职位</button><button onClick={()=>props.notify("新增正式职位需要逐项确认")}>创建正式职位</button><button onClick={()=>props.notify("职位族选择面板已打开")}>映射到职位族</button><button onClick={()=>props.notify("外部 LMS 角色面板已打开")}>仅外部角色</button></>}<button onClick={()=>void mutate([item.id],"defer")}>延期</button><button onClick={()=>{setSelected(new Set([item.id]));setIgnoreConfirm(true)}}>忽略</button></div></div></article>)}</div>
    <div className="mapping-pagination"><button disabled={page<=1} onClick={()=>setPage(value=>Math.max(1,value-1))}>上一页</button><span>第 {Math.min(page,pages)} / {pages} 页</span><button disabled={page>=pages} onClick={()=>setPage(value=>Math.min(pages,value+1))}>下一页</button></div>
    <footer><span className={`wizard-validation ${props.complete?"good":""}`}>{props.blocked?`! 仍有 ${summary.unresolved} 个标签待处理，保存后可继续回来完成`:"✓ 所有必要标签已处理"}</span><button className="wizard-primary" disabled={props.blocked} onClick={()=>void props.onConfirm()}>确认映射并继续</button></footer>
  </section>;
}

function toItems(props:Pick<Props,"aliases"|"positionLabels"|"tree"|"positions"|"families">):MappingItem[]{
  const path=(id:string|null)=>{const node=props.tree.find(item=>item.id===id);return node?.pathIds.map(pathId=>props.tree.find(item=>item.id===pathId)?.nameZh).filter(Boolean).join(" / ")??null};
  const departmentItems:MappingItem[]=props.aliases.map(item=>({id:item.id,type:"department",sourceLabel:item.sourceValue,affectedRows:item.syntheticEmployeeCount,sourceSheet:item.sourceSheet,suggestedTarget:item.suggestionLabel,confidence:item.confidence,suggestionReason:item.suggestionReason,targetLabel:path(item.targetDepartmentId),status:item.resolutionType==="deferred"?(item.suggestedTargetId?"pending":"blocked"):item.resolutionType,blocked:item.resolutionType==="deferred"&&!item.suggestedTargetId,batchEligible:Boolean(item.suggestedTargetId)&&!item.suggestionLabel.includes("运营单元")}));
  const positionItems:MappingItem[]=props.positionLabels.map(item=>({id:item.id,type:"position",sourceLabel:item.sourceValue,affectedRows:item.syntheticEmployeeCount,sourceSheet:item.sourceSheet,suggestedTarget:props.positions.find(position=>position.id===item.suggestedPositionId)?.nameZh??props.families.find(family=>family.id===item.suggestedFamilyId)?.nameZh??null,confidence:item.confidence,suggestionReason:item.suggestionReason,targetLabel:props.positions.find(position=>position.id===item.targetPositionId)?.nameZh??props.families.find(family=>family.id===item.targetPositionFamilyId)?.nameZh??null,status:item.resolutionStatus==="deferred"?(item.suggestedPositionId||item.suggestedFamilyId?"pending":"blocked"):item.resolutionStatus,blocked:item.resolutionStatus==="deferred"&&!item.suggestedPositionId&&!item.suggestedFamilyId,batchEligible:Boolean(item.suggestedPositionId)}));
  return [...departmentItems,...positionItems];
}
