"use client";
import { useMemo, useState } from "react";
import type { DepartmentRepository } from "../repositories/contracts/department-repository.ts";
import type { DepartmentMovePreview, DepartmentNode, DepartmentNodeType } from "../repositories/contracts/organization-models.ts";

type Props = {
  tenantId: string; propertyId: string; tree: DepartmentNode[]; repository: DepartmentRepository;
  complete: boolean; onTreeChange: (tree: DepartmentNode[]) => void; onConfirm: () => Promise<void>; notify: (message: string) => void;
  onDraftChange?: (dirty: boolean) => void;
  runOperation: (action: () => Promise<void>) => Promise<boolean>;
  saving: boolean;
};
type EditMode = "create-root" | "create-child" | "rename" | "move" | null;
const nodeTypes: Array<[DepartmentNodeType,string]> = [["division","业务板块"],["department","部门"],["section","分部"],["team","团队"],["other","其他"]];

export function OrganizationSetupStep({tenantId,propertyId,tree,repository,complete,onTreeChange,onConfirm,notify,onDraftChange,runOperation,saving}:Props){
  const [selectedId,setSelectedId]=useState(tree[0]?.id ?? ""); const [mode,setMode]=useState<EditMode>(null); const [name,setName]=useState(""); const [nameEn,setNameEn]=useState(""); const [nodeType,setNodeType]=useState<DepartmentNodeType>("department"); const [moveTarget,setMoveTarget]=useState(""); const [preview,setPreview]=useState<DepartmentMovePreview|null>(null); const [error,setError]=useState("");
  const selected=tree.find(node=>node.id===selectedId) ?? tree[0];
  const byId=useMemo(()=>new Map(tree.map(node=>[node.id,node])),[tree]);
  const path=(node?:DepartmentNode)=>node?.pathIds.map(id=>byId.get(id)?.nameZh).filter(Boolean).join(" / ") ?? "未选择部门";
  const refresh=async()=>onTreeChange(await repository.listTree(propertyId));
  const closeEditor=()=>{setMode(null);setPreview(null);onDraftChange?.(false)};
  const open=(next:EditMode)=>{setMode(next);setError("");setPreview(null);setName(next==="rename"&&selected?selected.nameZh:"");setNameEn(next==="rename"&&selected?selected.nameEn??"":"");setNodeType(selected?.nodeType??"department");onDraftChange?.(true)};
  const save=async()=>{setError("");if(!name.trim()){setError("请输入部门名称");return}let successMessage="部门名称已更新";await runOperation(async()=>{if(mode==="rename"&&selected){await repository.updateNode({id:selected.id,expectedVersion:selected.version,nameZh:name,nameEn,sortOrder:selected.sortOrder,isActive:selected.isActive});}else{const parentId=mode==="create-child"?selected?.id??null:null;const created=await repository.createNode({tenantId,propertyId,parentId,nodeType,code:`setup-${Date.now()}`,nameZh:name,nameEn,sortOrder:tree.length*10+10});setSelectedId(created.id);successMessage=parentId?"下级部门已新增":"一级部门已新增";}await refresh();notify(successMessage);closeEditor()})};
  const reorder=async(direction:-1|1)=>{if(!selected)return;await runOperation(async()=>{await repository.updateNode({id:selected.id,expectedVersion:selected.version,nameZh:selected.nameZh,nameEn:selected.nameEn??"",sortOrder:selected.sortOrder+direction*10,isActive:selected.isActive});await refresh();notify(direction<0?"部门已向前排序":"部门已向后排序")})};
  const prepareMove=async()=>{if(!selected)return;try{setError("");setPreview(await repository.previewMove(selected.id,moveTarget||null));}catch(next){setPreview(null);setError(next instanceof Error?next.message:"无法移动部门")}};
  const confirmMove=async()=>{if(!selected||!preview)return;await runOperation(async()=>{await repository.moveNode(selected.id,moveTarget||null,selected.version);await refresh();closeEditor();notify("部门及其全部下级已移动")})};
  const toggleActive=async()=>{if(!selected)return;await runOperation(async()=>{await repository.setActive(selected.id,selected.version,!selected.isActive);await refresh();notify(selected.isActive?"部门已停用，历史记录仍保留":"部门已重新启用")})};
  return <section className="wizard-card"><header className="wizard-intro"><h3>在启用检查中确认第一版正式组织</h3><p>财务部与工程部可以是一级部门；楼层可位于 房务部 / 客房部 之下。运营单元用于场所或营业点，不形成独立权限范围。</p></header>
    <div className="wizard-organization-toolbar"><div><strong>正式部门</strong><small>{tree.filter(node=>node.isActive).length} 个有效节点</small></div><button className="wizard-primary" disabled={saving} onClick={()=>open("create-root")}>新增一级部门</button></div>
    {tree.length===0?<div className="wizard-empty"><span>组织架构从这里开始</span><h3>先新增一级部门</h3><p>例如房务部、财务部或工程部，再逐级建立下属部门。</p></div>:<div className="wizard-organization-editor"><nav aria-label="正式部门树">{tree.map(node=><button key={node.id} className={`${node.id===selected?.id?"selected":""} ${node.isActive?"":"inactive"}`} style={{paddingLeft:14+node.depth*18}} onClick={()=>{if(mode&&!window.confirm("当前部门编辑尚未保存，确定放弃并切换吗？"))return;setSelectedId(node.id);closeEditor()}}><i>{node.depth?"↳":"◆"}</i><span><strong>{node.nameZh}</strong><small>{node.nameEn||nodeTypes.find(x=>x[0]===node.nodeType)?.[1]}</small></span><em>{node.isActive?"有效":"停用"}</em></button>)}</nav>
      <section className="wizard-department-detail">{selected&&<><div className="wizard-department-title"><div><span>当前层级路径</span><h4>{selected.nameZh}</h4><p>{path(selected)}</p></div><em>{nodeTypes.find(x=>x[0]===selected.nodeType)?.[1]}</em></div><dl><div><dt>下级部门</dt><dd>{tree.filter(node=>node.parentId===selected.id).length}</dd></div><div><dt>当前状态</dt><dd>{selected.isActive?"有效":"已停用"}</dd></div><div><dt>权限说明</dt><dd>正式部门分支</dd></div></dl><div className="wizard-department-actions"><button disabled={saving} onClick={()=>open("create-child")}>新增下级部门</button><button disabled={saving} onClick={()=>open("rename")}>重命名</button><button disabled={saving} onClick={()=>void reorder(-1)}>向前排序</button><button disabled={saving} onClick={()=>void reorder(1)}>向后排序</button><button disabled={saving} onClick={()=>open("move")}>移动部门</button><button disabled={saving} className={selected.isActive?"risk":""} onClick={()=>void toggleActive()}>{selected.isActive?"停用":"启用"}</button></div></>}</section></div>}
    {mode&&mode!=="move"&&<div className="wizard-inline-panel"><div><span>{mode==="create-root"?"新增一级部门":mode==="create-child"?`在「${selected?.nameZh}」下新增`:"重命名部门"}</span><strong>保持正式组织名称清晰、可审计</strong></div><label>中文名称<input disabled={saving} value={name} onChange={event=>{setName(event.target.value);onDraftChange?.(true)}} autoFocus/></label><label>英文名称<input disabled={saving} value={nameEn} onChange={event=>{setNameEn(event.target.value);onDraftChange?.(true)}}/></label>{mode!=="rename"&&<label>节点类型<select disabled={saving} value={nodeType} onChange={event=>{setNodeType(event.target.value as DepartmentNodeType);onDraftChange?.(true)}}>{nodeTypes.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>}<div><button disabled={saving} onClick={closeEditor}>取消</button><button disabled={saving} className="wizard-primary" onClick={()=>void save()}>{saving?"保存中…":"保存部门"}</button></div></div>}
    {mode==="move"&&selected&&<div className="wizard-inline-panel move"><div><span>移动部门</span><strong>{path(selected)}</strong></div><label>新的上级部门<select disabled={saving} value={moveTarget} onChange={event=>{setMoveTarget(event.target.value);setPreview(null);onDraftChange?.(true)}}><option value="">设为一级部门</option>{tree.filter(node=>node.id!==selected.id).map(node=><option value={node.id} key={node.id}>{path(node)}</option>)}</select></label><button disabled={saving} onClick={()=>void prepareMove()}>移动影响预览</button>{preview&&<div className="wizard-move-preview"><strong>确认移动影响</strong><p>{preview.currentPath} → {preview.proposedPath}</p><ul><li>{preview.childDepartmentsAffected} 个下级部门将一同移动</li><li>员工影响信息尚未接入；移动前请核对部门使用情况</li><li>{preview.aliasesAffected} 个别名、{preview.operationalUnitsAffected} 个运营单元受影响</li></ul><button disabled={saving} className="wizard-primary" onClick={()=>void confirmMove()}>{saving?"保存中…":"确认移动全部下级"}</button></div>}</div>}
    {error&&<div role="alert" className="wizard-error">{error}</div>}
    <div className="wizard-operational-note"><strong>正式部门与运营单元不同</strong><p>餐厅、酒吧、厨房或康体场所可作为运营单元附属于一个正式部门，不会自动获得独立权限范围。</p></div>
    <footer><span className={`wizard-validation ${complete?"good":""}`}>{complete?"✓ 已有有效正式部门":"! 酒店启用至少需要一个有效正式部门"}</span><button className="wizard-primary" disabled={!tree.some(node=>node.isActive)} onClick={()=>{onDraftChange?.(false);void onConfirm()}}>确认正式部门并继续</button></footer>
  </section>;
}
