"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { AppProviders } from "../providers";
import { createRepositoryRegistry } from "../repositories/registry.ts";
import type { DepartmentAlias, DepartmentNode, OfficialPosition, PositionFamily, PositionSourceLabel } from "../repositories/contracts/organization-models.ts";
import type { HotelPropertyRecord, PropertyIdentity, PropertySettings } from "../repositories/contracts/models.ts";
import { deriveWizardState, type WizardStepKey } from "../services/initialization-wizard-service.ts";
import { usePrototypeFeedback } from "../state/prototype-feedback";
import { useMockRole } from "../state/mock-role";

const stepKeys: WizardStepKey[] = ["identity","rules","organization","positions","upload","mapping","access","readiness"];
function Wizard() {
  const registry = useMemo(() => createRepositoryRegistry(), []); const router = useRouter(); const { showToast } = usePrototypeFeedback(); const { role } = useMockRole();
  const [record, setRecord] = useState<HotelPropertyRecord | null>(null); const [tree, setTree] = useState<DepartmentNode[]>([]); const [families, setFamilies] = useState<PositionFamily[]>([]); const [positions, setPositions] = useState<OfficialPosition[]>([]); const [aliases, setAliases] = useState<DepartmentAlias[]>([]); const [positionLabels, setPositionLabels] = useState<PositionSourceLabel[]>([]); const [progress, setProgress] = useState<any>({lastActiveStep:1,steps:{},version:1,completedAt:null});
  const [step, setStep] = useState(1); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [dirty, setDirty] = useState(false); const [newDepartment, setNewDepartment] = useState("");
  const hostname = registry.environment.dataMode === "mock" ? "training-demo.example.test" : registry.environment.devPropertyHostname ?? registry.environment.previewPropertyHostname ?? "";
  const load = async () => { const context = await registry.property.resolveContext(hostname); if (!context) throw new Error("酒店上下文尚未配置"); const [next, nodes, nextFamilies, nextPositions, nextAliases, nextLabels, nextProgress] = await Promise.all([registry.property.getProperty(context.propertyId), registry.department.listTree(context.propertyId), registry.position.listPositionFamilies(context.propertyId), registry.position.listPositions(context.propertyId), registry.department.listAliases(context.propertyId), registry.position.listSourceLabels(context.propertyId), registry.initialization.getProgress(context.propertyId)]); setRecord(next); setTree(nodes); setFamilies(nextFamilies); setPositions(nextPositions); setAliases(nextAliases); setPositionLabels(nextLabels); setProgress(nextProgress); setStep(Math.min(8, Math.max(1, nextProgress.lastActiveStep))); };
  useEffect(() => { void load().finally(() => setLoading(false)); }, []);
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (dirty) { event.preventDefault(); event.returnValue = "初始化资料尚未保存"; } }; addEventListener("beforeunload", warn); return () => removeEventListener("beforeunload", warn); }, [dirty]);
  if (loading) return <div className="wizard-loading">正在准备酒店初始化…</div>;
  if (role !== "ld_manager") return <div className="wizard-denied"><span>访问受限</span><h1>酒店尚未完成初始化</h1><p>仅 Property L&amp;D Manager 可继续酒店初始化。请联系当前酒店管理员。</p></div>;
  if (!record) return null;
  const state = deriveWizardState({ identity: record.identity, rules: record.settings, activeDepartments: tree.filter(x=>x.isActive).length, activePositions: positions.filter(x=>x.isActive).length, inspectedEmployeeMaster: true, unresolvedDepartmentLabels: aliases.filter(x=>x.resolutionType === "deferred").length, unresolvedPositionLabels: positionLabels.filter(x=>x.resolutionStatus === "deferred").length, activePropertyAdministrator: true, progress });
  const current = state.steps[step - 1]; const changeStep = async (next: number) => { if (dirty && !confirm("当前步骤有未保存的更改，确定离开吗？")) return; setDirty(false); setStep(next); setProgress(await registry.initialization.saveStep({propertyId:record.identity.id,stepKey:stepKeys[Math.min(step - 1, 6)],lastActiveStep:next,expectedVersion:progress.version})); };
  const saveIdentity = async () => { setSaving(true); try { const next = await registry.property.saveIdentity({propertyId:record.identity.id,expectedUpdatedAt:record.identity.updatedAt,code:record.identity.code,nameZh:record.identity.nameZh,nameEn:record.identity.nameEn,shortName:record.identity.shortName,brand:record.identity.brand,city:record.identity.city,countryRegion:record.identity.countryRegion,timezone:record.identity.timezone,defaultLanguage:record.identity.defaultLanguage}); setRecord(next); setDirty(false); showToast("酒店基本信息已保存"); await changeStep(2); } finally { setSaving(false); } };
  const saveRules = async () => { setSaving(true); try { const next = await registry.property.saveBusinessRules({propertyId:record.settings.propertyId,expectedVersion:record.settings.version,newEmployeeDays:record.settings.newEmployeeDays,probationFieldMeaning:record.settings.probationFieldMeaning,employeeStatusSource:record.settings.employeeStatusSource,ctcMandatory:record.settings.ctcMandatory,gtcMandatory:record.settings.gtcMandatory}); setRecord(next); setDirty(false); showToast("业务规则已保存"); await changeStep(3); } finally { setSaving(false); } };
  const confirmStep = async (key: WizardStepKey, next: number) => { setProgress(await registry.initialization.saveStep({propertyId:record.identity.id,stepKey:key,lastActiveStep:next,explicitlyConfirmed:true,expectedVersion:progress.version})); setDirty(false); setStep(next); showToast("当前步骤已保存"); };
  const resolveDepartment = async (alias: DepartmentAlias) => { await registry.department.approveMapping({aliasId:alias.id,action:"department",targetDepartmentId:alias.suggestedTargetId ?? tree[0]?.id}); setAliases(await registry.department.listAliases(record.identity.id)); showToast("部门来源标签已保存为别名"); };
  const resolvePosition = async (label: PositionSourceLabel) => { await registry.position.approvePositionMapping({sourceLabelId:label.id,action:"position",targetPositionId:label.suggestedPositionId ?? positions[0]?.id,targetPositionFamilyId:label.suggestedFamilyId ?? families[0]?.id}); setPositionLabels(await registry.position.listSourceLabels(record.identity.id)); showToast("职位来源标签已保存"); };
  const complete = async () => { if (!state.ready) return showToast("仍有必填步骤未完成，请查看阻塞项"); await registry.initialization.complete(record.identity.id, progress.version); showToast("酒店初始化已完成，正在进入系统"); router.replace("/"); };
  const identity = record.identity; const settings = record.settings;
  return <div className="initialization-shell"><header className="wizard-top"><a className="wizard-brand" href="/initialize"><i>澜</i><span><strong>酒店学习与发展</strong><small>Hotel L&amp;D Operations</small></span></a><div className="wizard-top-status"><span className="save-dot"/>本地示范资料已保护 <small>Auto-save available</small></div><div><button onClick={()=>showToast("帮助中心将在正式上线时开放")}>帮助</button><button onClick={()=>{setDirty(false);showToast("进度已保存，可随时继续")}}>保存并稍后继续</button></div></header>
    <div className="wizard-frame"><aside className="wizard-steps" aria-label="初始化步骤"><div><span>酒店初始化</span><h1>从基础资料到可用系统</h1></div>{state.steps.map(item=><button key={item.key} className={`${item.number===step?"active":""} ${item.complete?"complete":""} ${item.blocked?"blocked":""}`} onClick={()=>void changeStep(item.number)}><i>{item.complete?"✓":item.number}</i><span><strong>{item.label}</strong><small>{item.english}</small></span><em>{item.blocked?"需处理":item.complete?"已完成":""}</em></button>)}</aside>
      <main className="wizard-workspace"><header className="wizard-heading"><div><span>第 {step} 步 / 共 8 步</span><h2>{current.label}</h2><p>{current.english} · 一次只完成一个关键决定</p></div><button className="wizard-exit" onClick={()=>showToast("已保存当前进度；下次将回到此步骤")}>退出并稍后继续</button></header>
        {step===1 && <section className="wizard-card"><Intro title="让酒店在系统中被准确识别" detail="正式名称、物业代码与时区会用于应用导航、权限和后续运营报表。"/><div className="wizard-form">{([['nameZh','酒店正式中文名'],['nameEn','酒店正式英文名'],['shortName','酒店简称'],['code','物业代码'],['brand','品牌'],['city','城市'],['countryRegion','国家或地区'],['timezone','时区']] as const).map(([key,label])=><label key={key}><span>{label}</span><input value={identity[key]} onChange={e=>{setRecord({...record,identity:{...identity,[key]:e.target.value}});setDirty(true)}}/></label>)}<label><span>默认语言</span><select value={identity.defaultLanguage} onChange={e=>{setRecord({...record,identity:{...identity,defaultLanguage:e.target.value}});setDirty(true)}}><option value="zh-CN">简体中文</option><option value="en">English</option></select></label><div className="wizard-logo"><span>{identity.nameZh.slice(0,1)}</span><div><strong>酒店 Logo</strong><small>可选，支持 PNG、JPEG、WebP；可稍后在酒店设置维护。</small><button onClick={()=>showToast("本地示范模式：Logo 上传面板已准备")}>选择 Logo</button></div></div></div><footer><Validation complete={state.steps[0].complete} label="已验证必填酒店资料"/><button className="wizard-primary" disabled={saving} onClick={()=>void saveIdentity()}>{saving?"正在保存…":"保存并继续"}</button></footer></section>}
        {step===2 && <section className="wizard-card"><Intro title="定义本酒店的培训运营口径" detail="这些规则用于解释员工主数据和后续训练合规，不会使用技术字段名称。"/><div className="wizard-rules"><label><span><strong>新员工定义天数</strong><small>入职后多少天内属于新员工</small></span><input type="number" min="1" max="365" value={settings.newEmployeeDays} onChange={e=>{setRecord({...record,settings:{...settings,newEmployeeDays:Number(e.target.value)}});setDirty(true)}}/></label><Choice label="Probation 字段含义" value={settings.probationFieldMeaning} options={[["confirmation_date","转正日期"],["probation_end_date","试用期结束日期"],["unused","暂不使用"]]} onChange={value=>{setRecord({...record,settings:{...settings,probationFieldMeaning:value as any}});setDirty(true)}}/><Choice label="员工状态来源" value={settings.employeeStatusSource} options={[["manual","人工维护"],["excel_import","Excel 导入"],["future_hris","未来 HRIS"]]} onChange={value=>{setRecord({...record,settings:{...settings,employeeStatusSource:value as any}});setDirty(true)}}/>{([['ctcMandatory','CTC 必修'],['gtcMandatory','GTC 必修']] as const).map(([key,label])=><label className="wizard-toggle" key={key}><span><strong>{label}</strong><small>可在后续 KPI 口径中继续调整</small></span><input type="checkbox" checked={settings[key]} onChange={e=>{setRecord({...record,settings:{...settings,[key]:e.target.checked}});setDirty(true)}}/><i/></label>)}</div><footer><Validation complete={state.steps[1].complete} label="业务规则可用于员工主数据校验"/><button className="wizard-primary" disabled={saving} onClick={()=>void saveRules()}>{saving?"正在保存…":"保存并继续"}</button></footer></section>}
        {step===3 && <section className="wizard-card"><Intro title="建立正式组织架构，而不是复制来源标签" detail="财务与工程可以是一级部门；Floor 可以位于 房务部 › 客房部 之下。运营单元不承担独立权限范围。"/>{tree.length===0?<div className="wizard-empty"><span>组织架构从这里开始</span><h3>先新增一级部门</h3><p>例如：房务部、财务部或工程部。之后再逐级建立下属部门。</p></div>:<div className="wizard-tree">{tree.map(node=><div key={node.id} style={{paddingLeft:node.depth*24}}><i>{node.depth?"↳":"◆"}</i><strong>{node.nameZh}</strong><small>{node.nameEn} · 层级 {node.depth+1}</small></div>)}</div>}<div className="wizard-inline-create"><input placeholder="新增一级部门名称" value={newDepartment} onChange={e=>setNewDepartment(e.target.value)}/><button className="wizard-primary" onClick={async()=>{if(!newDepartment.trim())return showToast("请输入部门名称");await registry.department.createNode({tenantId:identity.tenantId,propertyId:identity.id,parentId:null,nodeType:"department",code:newDepartment.toLowerCase().replaceAll(/\s+/g,"-"),nameZh:newDepartment,nameEn:"",sortOrder:99});setTree(await registry.department.listTree(identity.id));setNewDepartment("");showToast("一级部门已新增")}}>新增一级部门</button><button onClick={()=>showToast("选择现有节点后可新增子部门、重命名、排序或移动")}>新增子部门</button></div><footer><Validation complete={state.steps[2].complete} label="至少一个有效正式部门"/><button className="wizard-primary" onClick={()=>void changeStep(4)}>继续</button></footer></section>}
        {step===4 && <section className="wizard-card"><Intro title="确认职位体系可服务于真实酒店岗位" detail="职位族用于归类；正式职位用于员工归属；来源职位标签只用于导入时的映射。"/><div className="wizard-grid-list"><article><span>职位族</span><strong>{families.length}</strong><small>{families.map(x=>x.nameZh).join(" · ")}</small><button onClick={()=>showToast("职位族新增与编辑面板已打开")}>管理职位族</button></article><article><span>正式职位</span><strong>{positions.length}</strong><small>可分配到一个或多个正式部门</small><button onClick={()=>showToast("正式职位新增面板已打开")}>新增正式职位</button></article><article><span>来源职位标签</span><strong>{positionLabels.length}</strong><small>{positionLabels.filter(x=>x.resolutionStatus==='deferred').length} 个待认领</small><button onClick={()=>void changeStep(6)}>前往认领</button></article></div><footer><Validation complete={state.steps[3].complete} label="需要管理员明确确认初始职位体系"/><button className="wizard-primary" onClick={()=>void confirmStep("positions",5)}>确认职位体系并继续</button></footer></section>}
        {step===5 && <section className="wizard-card"><Intro title="先检查，再导入" detail="员工资料会先进入受控暂存区；本检查点不导入培训历史、CTC 或 GTC 完成记录。"/><div className="wizard-inspection"><div><span>员工主数据工作簿</span><strong>本地合成示范文件</strong><small>仅演示选择、检查、表头识别和字段映射；尚未导入任何员工。</small></div><button className="wizard-primary" onClick={async()=>{const batch=(await registry.import.listImportHistory(identity.id))[0];await registry.import.inspectWorkbook(batch.id);showToast("文件检查完成：已识别员工主数据工作表")}}>检查文件</button></div><div className="wizard-grid-list compact"><article><span>工作表</span><strong>员工主数据</strong><small>仅选择包含员工主数据的工作表</small></article><article><span>字段映射</span><strong>已准备</strong><small>工号、姓名、部门、职位、日期</small></article><article><span>明确排除</span><strong>培训历史</strong><small>CTC/GTC 和课程列不会进入本次导入</small></article></div><footer><Validation complete={state.steps[4].complete} label="员工记录仍未导入"/><button className="wizard-primary" onClick={()=>void confirmStep("upload",6)}>确认检查结果并继续</button></footer></section>}
        {step===6 && <section className="wizard-card"><Intro title="认领每一个来源标签，才允许员工入库" detail="系统可以建议，但绝不会自动修改正式组织架构或职位体系。延期的必要标签会阻塞导入。"/><div className="mapping-split"><section><h3>部门标签 <small>Department labels</small></h3>{aliases.map(item=><div className="mapping-row" key={item.id}><span><strong>{item.sourceValue}</strong><small>{item.syntheticEmployeeCount} 条受影响记录 · 建议 {item.suggestionLabel}</small></span><em>{item.resolutionType==='deferred'?"待处理":"已处理"}</em>{item.resolutionType==='deferred'&&<button onClick={()=>void resolveDepartment(item)}>映射并保存</button>}</div>)}</section><section><h3>职位标签 <small>Position labels</small></h3>{positionLabels.map(item=><div className="mapping-row" key={item.id}><span><strong>{item.sourceValue}</strong><small>{item.syntheticEmployeeCount} 条受影响记录 · 置信度 {item.confidence}%</small></span><em>{item.resolutionStatus==='deferred'?"待处理":"已处理"}</em>{item.resolutionStatus==='deferred'&&<button onClick={()=>void resolvePosition(item)}>映射并保存</button>}</div>)}</section></div><footer><Validation complete={state.steps[5].complete} label={state.steps[5].blocked?"仍有延期来源标签，无法继续":"所有必要标签已处理"}/><button className="wizard-primary" disabled={state.steps[5].blocked} onClick={()=>void confirmStep("mapping",7)}>确认映射并继续</button></footer></section>}
        {step===7 && <section className="wizard-card"><Intro title="确认谁能维护这家酒店的培训运营" detail="当前 Property L&D Manager 可维护酒店基础资料；部门培训管理员只在被分配的部门范围内工作。"/><div className="wizard-access"><article><span>当前酒店管理员</span><strong>本地示范 L&amp;D Manager</strong><small>可维护酒店设置、组织、职位与受控导入。</small></article><article><span>部门培训管理员</span><strong>可选配置</strong><small>后续可按正式部门分支分配查看、提醒、考勤和反馈范围。</small><button onClick={()=>showToast("本地示范：部门范围预览已打开")}>查看部门范围</button></article></div><footer><Validation complete={state.steps[6].complete} label="至少一位酒店管理员处于活动状态"/><button className="wizard-primary" onClick={()=>void confirmStep("access",8)}>确认访问安排并继续</button></footer></section>}
        {step===8 && <section className="wizard-card readiness-card"><Intro title="准备进入酒店学习与发展运营系统" detail="以下检查来自已保存的酒店资料、组织、职位、文件检查和管理员确认，而非单一开关。"/><div className="readiness-list">{state.steps.slice(0,7).map(item=><div className={item.complete?"complete":item.blocked?"blocked":"pending"} key={item.key}><i>{item.complete?"✓":"!"}</i><span><strong>{item.label}</strong><small>{item.complete?"已完成，可在后续维护页面继续编辑":item.blocked?"存在阻塞项，需要返回处理":"尚未完成"}</small></span><button onClick={()=>void changeStep(item.number)}>查看</button></div>)}</div><footer><Validation complete={state.ready} label={state.ready?"全部必填检查已通过":"请先处理所有阻塞项"}/><button className="wizard-primary" disabled={!state.ready} onClick={()=>void complete()}>进入系统</button></footer></section>}
      </main><aside className="wizard-summary"><span>初始化进度</span><strong>{state.progressPercent}<small>%</small></strong><div className="wizard-progress"><i style={{width:`${state.progressPercent}%`}}/></div><dl><div><dt>已完成</dt><dd>{state.completedSteps.length} / 8</dd></div><div><dt>阻塞项</dt><dd className={state.steps.filter(x=>x.blocked).length?"risk":"good"}>{state.steps.filter(x=>x.blocked).length}</dd></div><div><dt>下一步</dt><dd>{state.steps.find(x=>!x.complete)?.label ?? "进入系统"}</dd></div></dl><div className="wizard-note"><strong>后续仍可编辑</strong><p>酒店设置、组织架构、职位体系、认领映射与导入中心会在初始化后作为日常维护入口保留。</p></div></aside>
    </div></div>;
}
function Intro({title,detail}:{title:string;detail:string}){return <header className="wizard-intro"><h3>{title}</h3><p>{detail}</p></header>}
function Validation({complete,label}:{complete:boolean;label:string}){return <span className={`wizard-validation ${complete?"good":""}`}>{complete?"✓":"!"} {label}</span>}
function Choice({label,value,options,onChange}:{label:string;value:string;options:string[][];onChange:(value:string)=>void}){return <label className="wizard-choice"><span><strong>{label}</strong></span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,n])=><option value={v} key={v}>{n}</option>)}</select></label>}
export default function InitializationPage(){return <AppProviders><Wizard/></AppProviders>}
