"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { ProtectedAppProviders } from "../providers";
import { createRepositoryRegistry } from "../repositories/registry.ts";
import type { DepartmentAlias, DepartmentNode, OfficialPosition, PositionFamily, PositionSourceLabel } from "../repositories/contracts/organization-models.ts";
import type { HotelPropertyRecord, PropertySettings } from "../repositories/contracts/models.ts";
import { deriveWizardState, type WizardProgress, type WizardStepKey } from "../services/initialization-wizard-service.ts";
import { usePrototypeFeedback } from "../state/prototype-feedback";
import { useAuthSession } from "../state/auth-session";
import { saveStateLabel } from "../services/save-state.ts";
import { OrganizationSetupStep } from "./OrganizationSetupStep.tsx";
import { WorkbookSetupStep } from "./WorkbookSetupStep.tsx";
import { MappingSetupStep } from "./MappingSetupStep.tsx";
import { PositionSetupStep } from "./PositionSetupStep.tsx";
import { AccessSetupStep } from "./AccessSetupStep.tsx";
import type { InitializationAccessSummary } from "../repositories/contracts/initialization-repository.ts";

function Wizard() {
  const registry = useMemo(() => createRepositoryRegistry(), []); const router = useRouter(); const { showToast } = usePrototypeFeedback(); const { session } = useAuthSession();
  const [record, setRecord] = useState<HotelPropertyRecord | null>(null); const [tree, setTree] = useState<DepartmentNode[]>([]); const [families, setFamilies] = useState<PositionFamily[]>([]); const [positions, setPositions] = useState<OfficialPosition[]>([]); const [aliases, setAliases] = useState<DepartmentAlias[]>([]); const [positionLabels, setPositionLabels] = useState<PositionSourceLabel[]>([]); const [progress, setProgress] = useState<WizardProgress & {version:number;completedAt:string|null}>({lastActiveStep:1,steps:{},version:1,completedAt:null});
  const [step, setStep] = useState(1); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [dirty, setDirty] = useState(false); const [saveError,setSaveError]=useState<string|null>(null);const[savedAt,setSavedAt]=useState<string|null>(null);const [inspectedEmployeeMaster,setInspectedEmployeeMaster]=useState(false);const[accessSummary,setAccessSummary]=useState<InitializationAccessSummary|null>(null);const[accessLoading,setAccessLoading]=useState(true);const logoInput=useRef<HTMLInputElement>(null);
  const load = useCallback(async () => { const propertyId=registry.environment.dataMode==="mock"?(await registry.property.resolveContext("training-demo.example.test"))?.propertyId:session.propertyId;if(!propertyId)throw new Error("酒店上下文尚未配置"); const [next, nodes, nextFamilies, nextPositions, nextAliases, nextLabels, nextProgress, batches, access] = await Promise.all([registry.property.getProperty(propertyId), registry.department.listTree(propertyId), registry.position.listPositionFamilies(propertyId), registry.position.listPositions(propertyId), registry.department.listAliases(propertyId), registry.position.listSourceLabels(propertyId), registry.initialization.getProgress(propertyId), registry.import.listImportHistory(propertyId),registry.initialization.getAccessSummary(propertyId)]); setRecord(next); setTree(nodes); setFamilies(nextFamilies); setPositions(nextPositions); setAliases(nextAliases); setPositionLabels(nextLabels); setProgress(nextProgress);setAccessSummary(access);setAccessLoading(false); setInspectedEmployeeMaster(batches.some(batch=>["mapping_required","validating","ready_for_review","importing","completed","completed_with_warnings"].includes(batch.status))); setStep(Math.min(8, Math.max(1, nextProgress.lastActiveStep))); }, [registry,session.propertyId]);
  useEffect(() => { let active=true; queueMicrotask(()=>{if(active)void load().finally(()=>setLoading(false))}); return()=>{active=false}; }, [load]);
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (dirty) { event.preventDefault(); event.returnValue = "初始化资料尚未保存"; } }; addEventListener("beforeunload", warn); return () => removeEventListener("beforeunload", warn); }, [dirty]);
  if (loading) return <div className="wizard-loading">正在准备酒店初始化…</div>;
  if (session.role!=="property_ld_manager") return <div className="wizard-denied"><span>访问受限</span><h1>当前账号无权编辑酒店启用检查</h1><p>只有当前酒店的学习与发展经理可以维护酒店启用资料。</p></div>;
  if (!record) return null;
  const state = deriveWizardState({ identity: record.identity, rules: record.settings, activeDepartments: tree.filter(x=>x.isActive).length, activePositions: positions.filter(x=>x.isActive).length, inspectedEmployeeMaster, unresolvedDepartmentLabels: aliases.filter(x=>x.resolutionType === "deferred").length, unresolvedPositionLabels: positionLabels.filter(x=>x.resolutionStatus === "deferred").length, activePropertyAdministrator: Boolean(accessSummary?.activePropertyManagers), progress });
  const current = state.steps[step - 1];
  const markSaved=()=>{setDirty(false);setSaveError(null);setSavedAt(new Intl.DateTimeFormat("zh-CN",{hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date()))};
  const changeStep = async (next: number) => { if(next===step)return;if (dirty && !confirm("当前步骤有未保存的更改，确定离开吗？")) return;setStep(next);setDirty(false);setSaving(true);setSaveError(null);try{const saved=await registry.initialization.saveNavigation(record.identity.id,next,progress.version);setProgress(saved)}catch(error){setSaveError(error instanceof Error?error.message:"已切换页面，但浏览位置保存失败")}finally{setSaving(false)} };
  const reloadPersisted=async(nextStep:number)=>{await load();const latest=await registry.initialization.getProgress(record.identity.id);setProgress(latest);setStep(nextStep);markSaved()};
  const saveIdentity = async () => { setSaving(true);setSaveError(null);try { await registry.property.saveIdentity({propertyId:record.identity.id,expectedUpdatedAt:record.identity.updatedAt,code:record.identity.code,nameZh:record.identity.nameZh,nameEn:record.identity.nameEn,shortName:record.identity.shortName,brand:record.identity.brand,city:record.identity.city,countryRegion:record.identity.countryRegion,timezone:record.identity.timezone,defaultLanguage:record.identity.defaultLanguage}); const saved=await registry.initialization.saveStep({propertyId:record.identity.id,stepKey:"identity",lastActiveStep:2,expectedVersion:progress.version});setProgress(saved);await reloadPersisted(2);showToast("酒店基本信息已保存"); }catch(error){setSaveError(error instanceof Error?error.message:"保存失败，请重试")}finally { setSaving(false); } };
  const saveRules = async () => { setSaving(true);setSaveError(null);try { const updatedRecord=await registry.property.saveBusinessRules({propertyId:record.settings.propertyId,expectedVersion:progress.version,newEmployeeDays:record.settings.newEmployeeDays,probationFieldMeaning:record.settings.probationFieldMeaning,employeeStatusSource:record.settings.employeeStatusSource,ctcMandatory:record.settings.ctcMandatory,gtcMandatory:record.settings.gtcMandatory}); const saved=await registry.initialization.saveStep({propertyId:record.identity.id,stepKey:"rules",lastActiveStep:3,expectedVersion:updatedRecord.settings.version});setProgress(saved);await reloadPersisted(3);showToast("业务规则已保存"); }catch(error){setSaveError(error instanceof Error?error.message:"保存失败，请重试")}finally { setSaving(false); } };
  const uploadLogo=async(file?:File)=>{if(!file)return;setSaving(true);setSaveError(null);try{const asset=await registry.property.uploadLogo({tenantId:record.identity.tenantId,propertyId:record.identity.id,file});setRecord({...record,currentLogo:asset});markSaved();showToast("酒店 Logo 已上传并设为当前版本")}catch(error){setSaveError(error instanceof Error?error.message:"Logo 上传失败，请重试")}finally{setSaving(false)}};
  const refreshAccess=async()=>{setAccessLoading(true);try{setAccessSummary(await registry.initialization.getAccessSummary(record.identity.id))}catch(error){setSaveError(error instanceof Error?error.message:"管理员状态读取失败")}finally{setAccessLoading(false)}};
  const refreshAfterInspection=async()=>{const[nextAliases,nextLabels,batches]=await Promise.all([registry.department.listAliases(record.identity.id),registry.position.listSourceLabels(record.identity.id),registry.import.listImportHistory(record.identity.id)]);setAliases(nextAliases);setPositionLabels(nextLabels);setInspectedEmployeeMaster(batches.some(batch=>["mapping_required","validating","ready_for_review","importing","completed","completed_with_warnings"].includes(batch.status)))};
  const confirmStep = async (key: WizardStepKey, next: number) => {setSaving(true);setSaveError(null);try{const saved=await registry.initialization.saveStep({propertyId:record.identity.id,stepKey:key,lastActiveStep:next,explicitlyConfirmed:true,expectedVersion:progress.version});setProgress(saved);await reloadPersisted(next);showToast("当前步骤已保存")}catch(error){setSaveError(error instanceof Error?error.message:"保存失败，请重试")}finally{setSaving(false)} };
  const saveForLater = async () => {setSaving(true);setSaveError(null);try{const saved=await registry.initialization.saveNavigation(record.identity.id,step,progress.version);setProgress(saved);markSaved();showToast("当前进度已保存，下次将回到此步骤")}catch(error){setSaveError(error instanceof Error?error.message:"保存失败，请重试")}finally{setSaving(false)} };
  const complete = async () => { if (!state.ready) return showToast("仍有必填步骤未完成，请查看阻塞项"); await registry.initialization.complete(record.identity.id, progress.version); showToast("酒店初始化已完成，正在进入系统"); router.replace("/"); };
  const identity = record.identity; const settings = record.settings;
  const currentSaveLabel=saveStateLabel({saving,dirty,error:saveError,savedAt});
  return <div className="initialization-shell"><header className="wizard-top"><Link className="wizard-brand" href="/initialize"><i>澜</i><span><strong>酒店学习与发展</strong><small>Hotel L&amp;D Operations</small></span></Link><div className={`wizard-top-status ${saveError?"error":dirty?"dirty":""}`}><span className="save-dot"/>{currentSaveLabel}<small>Server-persisted setup state</small></div><div><Link className="wizard-return" href="/">返回运营首页</Link><button disabled title="帮助中心尚未接入">帮助</button><button disabled={saving} onClick={()=>void saveForLater()}>保存并稍后继续</button></div></header>
    <div className="wizard-frame"><aside className="wizard-steps" aria-label="初始化步骤"><div><span>酒店初始化</span><h1>建立可用酒店系统</h1></div>{state.steps.map(item=><button key={item.key} className={`${item.number===step?"active":""} ${item.complete?"complete":""} ${item.blocked?"blocked":""}`} onClick={()=>void changeStep(item.number)}><i>{item.complete?"✓":item.number}</i><span><strong>{item.label}</strong><small>{item.english}</small></span><em>{item.blocked?"需处理":item.complete?"已完成":""}</em></button>)}</aside>
      <main className="wizard-workspace"><header className="wizard-heading"><div><span>第 {step} 步 / 共 8 步</span><h2>{current.label}</h2><p>{current.english} · 一次只完成一个关键决定</p></div></header>
        {step===1 && <section className="wizard-card"><Intro title="让酒店在系统中被准确识别" detail="正式名称、物业代码与时区会用于应用导航、权限和后续运营报表。"/><div className="wizard-form">{([['nameZh','酒店正式中文名'],['nameEn','酒店正式英文名'],['shortName','酒店简称'],['code','物业代码'],['brand','品牌'],['city','城市'],['countryRegion','国家或地区'],['timezone','时区']] as const).map(([key,label])=><label key={key}><span>{label}</span><input value={identity[key]} onChange={e=>{setRecord({...record,identity:{...identity,[key]:e.target.value}});setDirty(true)}}/></label>)}<label><span>默认语言</span><select value={identity.defaultLanguage} onChange={e=>{setRecord({...record,identity:{...identity,defaultLanguage:e.target.value}});setDirty(true)}}><option value="zh-CN">简体中文</option><option value="en">English</option></select></label><div className="wizard-logo">{record.currentLogo?<img src={record.currentLogo.publicUrl} alt={`${identity.nameZh} Logo`}/>:<span>{identity.nameZh.slice(0,1)}</span>}<div><strong>酒店 Logo</strong><small>支持 PNG、JPEG、WebP，最大 2 MB；上传后立即用于登录页和酒店品牌展示。</small><input ref={logoInput} type="file" hidden accept="image/png,image/jpeg,image/webp" onChange={event=>void uploadLogo(event.target.files?.[0])}/><button disabled={saving} onClick={()=>logoInput.current?.click()}>{saving?"正在上传…":record.currentLogo?"更换 Logo":"上传 Logo"}</button></div></div></div><footer><Validation complete={state.steps[0].complete} label="已验证必填酒店资料"/><button className="wizard-primary" disabled={saving} onClick={()=>void saveIdentity()}>{saving?"正在保存…":"保存并继续"}</button></footer></section>}
        {step===2 && <section className="wizard-card"><Intro title="定义本酒店的培训运营口径" detail="这些规则用于解释员工主数据和后续训练合规，不会使用技术字段名称。"/><div className="wizard-rules"><label><span><strong>新员工定义天数</strong><small>入职后多少天内属于新员工</small></span><input type="number" min="1" max="365" value={settings.newEmployeeDays} onChange={e=>{setRecord({...record,settings:{...settings,newEmployeeDays:Number(e.target.value)}});setDirty(true)}}/></label><Choice label="Probation 字段含义" value={settings.probationFieldMeaning} options={[["confirmation_date","转正日期"],["probation_end_date","试用期结束日期"],["unused","暂不使用"]]} onChange={value=>{setRecord({...record,settings:{...settings,probationFieldMeaning:value as PropertySettings["probationFieldMeaning"]}});setDirty(true)}}/><Choice label="员工状态来源" value={settings.employeeStatusSource} options={[["manual","人工维护"],["excel_import","Excel 导入"],["future_hris","未来 HRIS"]]} onChange={value=>{setRecord({...record,settings:{...settings,employeeStatusSource:value as PropertySettings["employeeStatusSource"]}});setDirty(true)}}/>{([['ctcMandatory','CTC 必修'],['gtcMandatory','GTC 必修']] as const).map(([key,label])=><label className="wizard-toggle" key={key}><span><strong>{label}</strong><small>可在后续 KPI 口径中继续调整</small></span><input type="checkbox" checked={settings[key]} onChange={e=>{setRecord({...record,settings:{...settings,[key]:e.target.checked}});setDirty(true)}}/><i/></label>)}</div><footer><Validation complete={state.steps[1].complete} label="业务规则可用于员工主数据校验"/><button className="wizard-primary" disabled={saving} onClick={()=>void saveRules()}>{saving?"正在保存…":"保存并继续"}</button></footer></section>}
        {step===3 && <OrganizationSetupStep tenantId={identity.tenantId} propertyId={identity.id} tree={tree} repository={registry.department} complete={state.steps[2].complete} onTreeChange={setTree} onConfirm={()=>confirmStep("organization",4)} notify={showToast}/>}
        {step===4 && <PositionSetupStep tenantId={identity.tenantId} propertyId={identity.id} tree={tree} families={families} positions={positions} repository={registry.position} complete={state.steps[3].complete} onFamilies={setFamilies} onPositions={setPositions} onConfirm={()=>confirmStep("positions",5)} notify={showToast}/>}
        {step===5 && <WorkbookSetupStep propertyId={identity.id} repository={registry.import} realMode={registry.environment.dataMode!=="mock"} complete={state.steps[4].complete} persistedInspected={inspectedEmployeeMaster} onInspected={refreshAfterInspection} onConfirm={()=>confirmStep("upload",6)} notify={showToast}/>}
        {step===6 && <MappingSetupStep tenantId={identity.tenantId} propertyId={identity.id} aliases={aliases} positionLabels={positionLabels} tree={tree} positions={positions} families={families} departmentRepository={registry.department} positionRepository={registry.position} complete={state.steps[5].complete} blocked={state.steps[5].blocked} onAliases={setAliases} onPositions={setPositionLabels} onTree={setTree} onOfficialPositions={setPositions} onFamilies={setFamilies} onConfirm={()=>confirmStep("mapping",7)} notify={showToast}/>}
        {step===7 && <AccessSetupStep summary={accessSummary} loading={accessLoading} complete={state.steps[6].complete} onReload={refreshAccess} onConfirm={()=>confirmStep("access",8)}/>}
        {step===8 && <section className="wizard-card readiness-card"><Intro title="准备进入酒店学习与发展运营系统" detail="以下检查来自已保存的酒店资料、组织、职位、文件检查和管理员确认，而非单一开关。"/><div className="readiness-list">{state.steps.slice(0,7).map(item=><div className={item.complete?"complete":item.blocked?"blocked":"pending"} key={item.key}><i>{item.complete?"✓":"!"}</i><span><strong>{item.label}</strong><small>{item.complete?"已完成，可在后续维护页面继续编辑":item.blocked?"存在阻塞项，需要返回处理":"尚未完成"}</small></span><button onClick={()=>void changeStep(item.number)}>查看</button></div>)}</div><footer><Validation complete={state.ready} label={state.ready?"全部必填检查已通过":"请先处理所有阻塞项"}/><button className="wizard-primary" disabled={!state.ready} onClick={()=>void complete()}>进入系统</button></footer></section>}
      </main><aside className="wizard-summary"><span>初始化进度</span><strong>{state.progressPercent}<small>%</small></strong><div className="wizard-progress"><i style={{width:`${state.progressPercent}%`}}/></div><dl><div><dt>已完成</dt><dd>{state.completedSteps.length} / 8</dd></div><div><dt>阻塞项</dt><dd className={state.steps.filter(x=>x.blocked).length?"risk":"good"}>{state.steps.filter(x=>x.blocked).length}</dd></div><div><dt>下一建议</dt><dd>{state.nextRecommendedAction}</dd></div></dl><div className="wizard-note"><strong>进度计算说明</strong><p>八个必需步骤采用等权计算；每个步骤占 12.5%，以已保存事实和明确确认为准。刷新后结果保持一致。</p></div><div className="wizard-note secondary"><strong>后续仍可编辑</strong><p>酒店设置、组织架构、职位体系、认领映射与导入中心会在初始化后作为日常维护入口保留。</p></div></aside>
    </div></div>;
}
function Intro({title,detail}:{title:string;detail:string}){return <header className="wizard-intro"><h3>{title}</h3><p>{detail}</p></header>}
function Validation({complete,label}:{complete:boolean;label:string}){return <span className={`wizard-validation ${complete?"good":""}`}>{complete?"✓":"!"} {label}</span>}
function Choice({label,value,options,onChange}:{label:string;value:string;options:string[][];onChange:(value:string)=>void}){return <label className="wizard-choice"><span><strong>{label}</strong></span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,n])=><option value={v} key={v}>{n}</option>)}</select></label>}
export default function InitializationPage(){return <ProtectedAppProviders><Wizard/></ProtectedAppProviders>}
