"use client";
import { useState } from "react";
import type { PositionRepository } from "../repositories/contracts/position-repository.ts";
import type { DepartmentNode, OfficialPosition, PositionFamily } from "../repositories/contracts/organization-models.ts";

type Props={tenantId:string;propertyId:string;tree:DepartmentNode[];families:PositionFamily[];positions:OfficialPosition[];repository:PositionRepository;complete:boolean;onFamilies:(items:PositionFamily[])=>void;onPositions:(items:OfficialPosition[])=>void;onConfirm:()=>Promise<void>;notify:(message:string)=>void};
type Mode="family"|"position"|null;

export function PositionSetupStep(props:Props){
  const[mode,setMode]=useState<Mode>(null);const[editingFamily,setEditingFamily]=useState<PositionFamily|null>(null);const[editingPosition,setEditingPosition]=useState<OfficialPosition|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");
  const[familyDraft,setFamilyDraft]=useState({code:"",nameZh:"",nameEn:"",description:"",isActive:true});
  const[positionDraft,setPositionDraft]=useState({code:"",nameZh:"",nameEn:"",gradeOrBand:"",positionFamilyId:"",departmentIds:[] as string[],isActive:true});
  const refresh=async()=>{const[nextFamilies,nextPositions]=await Promise.all([props.repository.listPositionFamilies(props.propertyId),props.repository.listPositions(props.propertyId)]);props.onFamilies(nextFamilies);props.onPositions(nextPositions)};
  const openFamily=(family?:PositionFamily)=>{setMode("family");setEditingFamily(family??null);setError("");setFamilyDraft({code:family?.code??"",nameZh:family?.nameZh??"",nameEn:family?.nameEn??"",description:family?.description??"",isActive:family?.isActive??true})};
  const openPosition=(position?:OfficialPosition)=>{setMode("position");setEditingPosition(position??null);setError("");setPositionDraft({code:position?.code??"",nameZh:position?.nameZh??"",nameEn:position?.nameEn??"",gradeOrBand:position?.gradeOrBand??"",positionFamilyId:position?.positionFamilyId??"",departmentIds:position?.departmentIds??[],isActive:position?.isActive??true})};
  const saveFamily=async()=>{try{setBusy(true);setError("");if(!familyDraft.code.trim()||!familyDraft.nameZh.trim())throw new Error("请填写职位族代码和中文名称");await props.repository.savePositionFamily({id:editingFamily?.id,tenantId:props.tenantId,propertyId:props.propertyId,code:normalizedCode(familyDraft.code),nameZh:familyDraft.nameZh.trim(),nameEn:familyDraft.nameEn.trim()||null,description:familyDraft.description.trim()||null,sortOrder:editingFamily?.sortOrder??(props.families.length+1)*10,isActive:familyDraft.isActive});await refresh();setMode(null);props.notify(editingFamily?"职位族已更新":"职位族已创建")}catch(reason){setError(message(reason))}finally{setBusy(false)}};
  const savePosition=async()=>{try{setBusy(true);setError("");if(!positionDraft.code.trim()||!positionDraft.nameZh.trim())throw new Error("请填写职位代码和中文名称");if(!positionDraft.departmentIds.length)throw new Error("请至少选择一个适用部门");const saved=await props.repository.savePosition({id:editingPosition?.id,version:editingPosition?.version,tenantId:props.tenantId,propertyId:props.propertyId,positionFamilyId:positionDraft.positionFamilyId||null,code:normalizedCode(positionDraft.code),nameZh:positionDraft.nameZh.trim(),nameEn:positionDraft.nameEn.trim()||null,gradeOrBand:positionDraft.gradeOrBand.trim()||null,isActive:positionDraft.isActive});await props.repository.assignPositionToDepartments(saved.id,positionDraft.departmentIds);await refresh();setMode(null);props.notify(editingPosition?"正式职位已更新":"正式职位已创建")}catch(reason){setError(message(reason))}finally{setBusy(false)}};
  return <section className="wizard-card position-setup"><header className="wizard-intro"><h3>建立可维护的正式职位体系</h3><p>职位族用于归类，正式职位用于员工归属；来源职位标签只在下一步建立映射，不会替代正式职位。</p></header>
    <div className="position-setup-toolbar"><div><strong>{props.families.filter(item=>item.isActive).length} 个有效职位族</strong><small>{props.positions.filter(item=>item.isActive).length} 个有效正式职位</small></div><button onClick={()=>openFamily()}>新增职位族</button><button className="wizard-primary" onClick={()=>openPosition()}>新增正式职位</button></div>
    <div className="position-setup-grid"><section><header><strong>职位族</strong><small>Position families</small></header>{props.families.length?<div className="position-rows">{props.families.map(item=><button key={item.id} onClick={()=>openFamily(item)}><span><strong>{item.nameZh}</strong><small>{item.nameEn||item.code}</small></span><em>{item.isActive?"有效":"停用"}</em></button>)}</div>:<div className="wizard-empty compact"><h3>尚未建立职位族</h3><p>职位族可选，但有助于后续统计管理人员、主管和一线岗位。</p><button onClick={()=>openFamily()}>创建第一个职位族</button></div>}</section>
      <section><header><strong>正式职位</strong><small>Official positions</small></header>{props.positions.length?<div className="position-rows">{props.positions.map(item=><button key={item.id} onClick={()=>openPosition(item)}><span><strong>{item.nameZh}</strong><small>{item.nameEn||item.code} · {item.departmentIds.length} 个适用部门</small></span><em>{item.isActive?"有效":"停用"}</em></button>)}</div>:<div className="wizard-empty compact"><h3>尚未建立正式职位</h3><p>至少创建一个有效职位并分配到正式部门，才能确认本步骤。</p><button onClick={()=>openPosition()}>创建第一个正式职位</button></div>}</section></div>
    {mode==="family"&&<div className="wizard-inline-panel position-form" role="dialog" aria-label="职位族编辑"><div><span>{editingFamily?"编辑职位族":"新增职位族"}</span><strong>用于酒店岗位归类</strong></div><label>职位族代码<input value={familyDraft.code} placeholder="例如 manager" onChange={event=>setFamilyDraft({...familyDraft,code:event.target.value})}/></label><label>中文名称<input value={familyDraft.nameZh} onChange={event=>setFamilyDraft({...familyDraft,nameZh:event.target.value})}/></label><label>英文名称<input value={familyDraft.nameEn} onChange={event=>setFamilyDraft({...familyDraft,nameEn:event.target.value})}/></label><label>业务说明<input value={familyDraft.description} onChange={event=>setFamilyDraft({...familyDraft,description:event.target.value})}/></label><label className="position-active"><input type="checkbox" checked={familyDraft.isActive} onChange={event=>setFamilyDraft({...familyDraft,isActive:event.target.checked})}/>保持有效</label><div><button onClick={()=>setMode(null)}>取消</button><button className="wizard-primary" disabled={busy} onClick={()=>void saveFamily()}>{busy?"保存中…":"保存职位族"}</button></div></div>}
    {mode==="position"&&<div className="wizard-inline-panel position-form" role="dialog" aria-label="正式职位编辑"><div><span>{editingPosition?"编辑正式职位":"新增正式职位"}</span><strong>分配到一个或多个正式部门</strong></div><label>职位代码<input value={positionDraft.code} placeholder="例如 front-office-manager" onChange={event=>setPositionDraft({...positionDraft,code:event.target.value})}/></label><label>中文名称<input value={positionDraft.nameZh} onChange={event=>setPositionDraft({...positionDraft,nameZh:event.target.value})}/></label><label>英文名称<input value={positionDraft.nameEn} onChange={event=>setPositionDraft({...positionDraft,nameEn:event.target.value})}/></label><label>职级 / Band<input value={positionDraft.gradeOrBand} onChange={event=>setPositionDraft({...positionDraft,gradeOrBand:event.target.value})}/></label><label>职位族<select value={positionDraft.positionFamilyId} onChange={event=>setPositionDraft({...positionDraft,positionFamilyId:event.target.value})}><option value="">暂不归类</option>{props.families.filter(item=>item.isActive).map(item=><option value={item.id} key={item.id}>{item.nameZh}</option>)}</select></label><fieldset><legend>适用部门</legend>{props.tree.filter(item=>item.isActive).map(item=><label key={item.id} style={{paddingLeft:8+item.depth*12}}><input type="checkbox" checked={positionDraft.departmentIds.includes(item.id)} onChange={event=>setPositionDraft({...positionDraft,departmentIds:event.target.checked?[...positionDraft.departmentIds,item.id]:positionDraft.departmentIds.filter(id=>id!==item.id)})}/>{item.nameZh}</label>)}</fieldset><label className="position-active"><input type="checkbox" checked={positionDraft.isActive} onChange={event=>setPositionDraft({...positionDraft,isActive:event.target.checked})}/>保持有效</label><div><button onClick={()=>setMode(null)}>取消</button><button className="wizard-primary" disabled={busy} onClick={()=>void savePosition()}>{busy?"保存中…":"保存正式职位"}</button></div></div>}
    {error&&<div role="alert" className="wizard-error">{error}</div>}
    <footer><span className={`wizard-validation ${props.complete?"good":""}`}>{props.complete?"✓ 初始职位体系已确认":"! 至少需要一个有效正式职位，并由管理员确认"}</span><button className="wizard-primary" disabled={!props.positions.some(item=>item.isActive)||busy} onClick={()=>void props.onConfirm()}>确认职位体系并继续</button></footer>
  </section>;
}
function normalizedCode(value:string){const code=value.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");if(!code)throw new Error("代码仅支持英文字母、数字和连字符");return code}
function message(value:unknown){return value instanceof Error?value.message:"操作未完成，请重试"}
