"use client";
import { useRef, useState } from "react";
import type { ImportRepository } from "../repositories/contracts/import-repository.ts";
import type { WorkbookInspection } from "../services/import/workbook-parser.ts";
import type { EmployeeMasterAggregate } from "../services/import/workbook-parser.ts";

type FileState = "none" | "synthetic" | "real";
type Props={propertyId:string;repository:ImportRepository;complete:boolean;persistedInspected:boolean;onInspected:()=>void;onConfirm:()=>Promise<void>;notify:(message:string)=>void};
export function WorkbookSetupStep({propertyId,repository,complete,persistedInspected,onInspected,onConfirm,notify}:Props){
  const input=useRef<HTMLInputElement>(null);const selectedFile=useRef<File|null>(null);const [fileState,setFileState]=useState<FileState>(persistedInspected?"synthetic":"none");const [fileName,setFileName]=useState(persistedInspected?"synthetic_employee_master.xlsx":"");const [inspection,setInspection]=useState<WorkbookInspection|null>(null);const [aggregate,setAggregate]=useState<EmployeeMasterAggregate|null>(null);const [busy,setBusy]=useState(false);
  const choose=(file?:File)=>{if(!file)return;selectedFile.current=file;setFileName(file.name);setFileState(/synthetic|fixture|test/i.test(file.name)?"synthetic":"real");setInspection(null);setAggregate(null)};
  const inspect=async()=>{setBusy(true);try{if(fileState==="real"&&selectedFile.current){const form=new FormData();form.set("file",selectedFile.current);const response=await fetch("/api/local-workbook-inspection",{method:"POST",body:form});const payload=await response.json();if(!response.ok)throw new Error(payload.message);setAggregate(payload);setInspection(payload.workbook);}else{const batch=(await repository.listImportHistory(propertyId))[0];if(!batch)throw new Error("请先建立本地检查批次");setInspection(await repository.inspectWorkbook(batch.id));}onInspected();notify("文件检查完成；员工仍未导入");}catch(error){notify(error instanceof Error?error.message:"文件检查失败");}finally{setBusy(false)}};
  const title=fileState==="none"?"尚未选择文件":fileState==="synthetic"?"合成测试文件":"真实工作簿，仅本地检查，尚未提交";
  return <section className="wizard-card"><header className="wizard-intro"><h3>先检查，再进入受控暂存</h3><p>支持 XLS、XLSX、CSV，最大 25 MB。文件检查与员工导入是两个不同阶段；本步骤不写入正式员工资料。</p></header>
    <div className={`wizard-inspection ${fileState}`}><div><span>员工主数据工作簿</span><strong>{title}</strong><small>{fileState==="none"?"请选择本地文件。文件不会在本检查点上传到生产环境。":fileState==="synthetic"?`${fileName} · 明确标记为测试数据`:`${fileName} · 不显示本机完整路径，不上传生产环境`}</small></div><div><input ref={input} type="file" accept=".xls,.xlsx,.csv" hidden onChange={event=>choose(event.target.files?.[0])}/><button onClick={()=>input.current?.click()}>选择本地文件</button><button className="wizard-primary" disabled={fileState==="none"||busy} onClick={()=>void inspect()}>{busy?"检查中…":"检查文件"}</button></div></div>
    <div className="wizard-file-states"><article className={inspection?"complete":"active"}><i>{inspection?"✓":"1"}</i><span><strong>文件检查</strong><small>{inspection?`识别 ${inspection.sheets.length} 个工作表`:`${title} · 尚未检查`}</small></span></article><article className={inspection?"active":""}><i>2</i><span><strong>暂存准备</strong><small>{inspection?"已形成检查结果；等待认领来源标签":"尚未准备"}</small></span></article><article><i>3</i><span><strong>员工导入</strong><small>未执行；仅在最终确认后发生</small></span></article></div>
    {inspection&&<div className="wizard-inspection-results"><div><span>识别工作表</span><strong>{inspection.sheets.length}</strong><small>{inspection.sheets.map(sheet=>sheet.name).join(" · ")}</small></div><div><span>员工主表</span><strong>{aggregate?.selectedSheet??inspection.sheets[0]?.name}</strong><small>表头第 {aggregate?.headerRow??inspection.sheets[0]?.likelyHeaderRow??"—"} 行 · {aggregate?.employeeMaster.sourceRows??Math.max(0,(inspection.sheets[0]?.rowCount??0)-(inspection.sheets[0]?.likelyHeaderRow??0))} 条候选行</small></div><div><span>来源标签</span><strong>{aggregate?`${aggregate.mapping.uniqueDepartmentLabels} 部门 / ${aggregate.mapping.uniquePositionLabels} 职位`:"等待认领"}</strong><small>{aggregate?`${aggregate.employeeMaster.missingDepartments} 条缺少部门 · ${aggregate.warnings.length} 类警告`:"部门与职位标签会在下一步单独处理"}</small></div><div><span>明确排除</span><strong>培训历史 / CTC / GTC</strong><small>{aggregate?`${aggregate.exclusions.totalColumns} 个字段类别不进入员工主数据`:"公式列、课程历史与性别默认不进入员工主数据"}</small></div></div>}
    <div className="wizard-privacy-note"><strong>隐私边界</strong><p>本地选择不代表导入。工作簿先经过格式、表头、字段和警告检查；空白值不会被解释为停用、未完成或未分配。</p></div>
    <footer><span className={`wizard-validation ${complete?"good":""}`}>{complete?"✓ 检查事实和管理员确认已保存":"! 员工记录仍未导入"}</span><button className="wizard-primary" disabled={!inspection&&!persistedInspected} onClick={()=>void onConfirm()}>确认检查结果并继续</button></footer>
  </section>;
}
