import{parseAppEnvironment}from"../../lib/environment.ts";
import{cleanupMockLogos,getMockProperty,getMockPropertyContext,saveMockIdentity,saveMockLogo,saveMockRules}from"./store.ts";
import{requireLocalReviewManager}from"../../services/local-review-authorization.ts";
import{AuthorizationError}from"../../services/production-authorization.ts";
export async function GET(request:Request){if(!isLocalMock())return Response.json({message:"not found"},{status:404});const url=new URL(request.url);const hostname=url.searchParams.get("hostname");if(hostname){const context=getMockPropertyContext(hostname);return context?noStore(context):Response.json({message:"酒店域名尚未配置"},{status:404})}try{requireLocalReviewManager(request);return noStore(getMockProperty())}catch(error){return authFailure(error)}}
export async function POST(request:Request){if(!isLocalMock())return Response.json({message:"not found"},{status:404});try{requireLocalReviewManager(request);const body=await request.json();if(body.action==="rules")return noStore(saveMockRules(body.input));if(body.action==="logo")return noStore(saveMockLogo(body.input));if(body.action==="cleanup")return noStore(cleanupMockLogos(body.propertyId));return noStore(saveMockIdentity(body.input))}catch(error){if(error instanceof AuthorizationError)return authFailure(error);return Response.json({message:error instanceof Error?error.message:"保存失败"},{status:409,headers:{"Cache-Control":"no-store"}})}}
function isLocalMock(){try{const environment=parseAppEnvironment();return environment.appEnv==="local"&&environment.dataMode==="mock"}catch{return false}}
function noStore(value:unknown){return Response.json(value,{headers:{"Cache-Control":"no-store"}})}
function authFailure(error:unknown){return error instanceof AuthorizationError?Response.json({message:error.message},{status:error.status,headers:{"Cache-Control":"no-store"}}):Response.json({message:"访问被拒绝"},{status:403,headers:{"Cache-Control":"no-store"}})}
