import type{HotelPropertyRecord,PropertyBrandAsset,PropertyContext}from"../../repositories/contracts/models.ts";
import type{SaveBusinessRulesInput,SavePropertyIdentityInput}from"../../repositories/contracts/property-repository.ts";
const tenantId="10000000-0000-0000-0000-000000000001",propertyId="20000000-0000-0000-0000-000000000011",hostname="training-demo.example.test";
let record:HotelPropertyRecord={identity:{id:propertyId,tenantId,code:"DEMO-01",nameZh:"示范酒店",nameEn:"Synthetic Hotel",shortName:"示范酒店",brand:"Demo Hospitality",city:"测试城市",countryRegion:"CN",timezone:"Asia/Shanghai",defaultLanguage:"zh-CN",status:"initializing",updatedAt:"2026-07-13T00:00:00.000Z"},settings:{id:"30000000-0000-0000-0000-000000000011",propertyId,newEmployeeDays:90,probationFieldMeaning:"confirmation_date",employeeStatusSource:"manual",ctcMandatory:true,gtcMandatory:true,initializationState:"in_progress",version:1,updatedAt:"2026-07-13T00:00:00.000Z"},currentLogo:null};
const logoAssets:PropertyBrandAsset[]=[];
export function getMockProperty(){return structuredClone(record)}
export function getMockPropertyContext(candidate:string):PropertyContext|null{if(![hostname,"localhost","127.0.0.1"].includes(candidate.trim().toLowerCase()))return null;return{tenantId,propertyId,hostname,nameZh:record.identity.nameZh,nameEn:record.identity.nameEn,shortName:record.identity.shortName,logoUrl:record.currentLogo?.publicUrl??null}}
export function saveMockIdentity(input:SavePropertyIdentityInput){if(input.propertyId!==propertyId)throw new Error("未找到当前酒店资料");if(input.expectedUpdatedAt!==record.identity.updatedAt)throw new Error("酒店资料已被更新，请刷新后重试");for(const key of ["code","nameZh","nameEn","shortName","brand","city","countryRegion","timezone","defaultLanguage"] as const)if(!input[key].trim())throw new Error("酒店必填资料不能为空");record={...record,identity:{...record.identity,code:input.code.trim(),nameZh:input.nameZh.trim(),nameEn:input.nameEn.trim(),shortName:input.shortName.trim(),brand:input.brand.trim(),city:input.city.trim(),countryRegion:input.countryRegion.trim(),timezone:input.timezone.trim(),defaultLanguage:input.defaultLanguage.trim(),updatedAt:new Date().toISOString()}};return getMockProperty()}
export function saveMockRules(input:SaveBusinessRulesInput){if(input.propertyId!==propertyId)throw new Error("未找到当前酒店资料");if(input.expectedVersion!==record.settings.version)throw new Error("酒店资料已被更新，请刷新后重试");if(!Number.isInteger(input.newEmployeeDays)||input.newEmployeeDays<1||input.newEmployeeDays>365)throw new Error("新员工定义必须在 1 至 365 天之间");record={...record,settings:{...record.settings,newEmployeeDays:input.newEmployeeDays,probationFieldMeaning:input.probationFieldMeaning,employeeStatusSource:input.employeeStatusSource,ctcMandatory:Boolean(input.ctcMandatory),gtcMandatory:Boolean(input.gtcMandatory),version:record.settings.version+1,updatedAt:new Date().toISOString()}};return getMockProperty()}
export function saveMockLogo(input:{tenantId:string;propertyId:string;fileName:string;mimeType:PropertyBrandAsset["mimeType"];byteSize:number;dataUrl:string}){if(input.tenantId!==tenantId||input.propertyId!==propertyId)throw new Error("无权写入其他酒店的品牌路径");if(!["image/png","image/jpeg","image/webp"].includes(input.mimeType))throw new Error("仅支持 PNG、JPEG 或 WebP 酒店标识");if(input.byteSize>2*1024*1024)throw new Error("酒店标识不能超过 2 MB");if(!input.dataUrl.startsWith(`data:${input.mimeType};base64,`))throw new Error("酒店标识内容无效");const now=new Date();for(const asset of logoAssets){if(!asset.isCurrent)continue;asset.isCurrent=false;asset.retentionUntil=new Date(now.getTime()+30*86400000).toISOString()}const id=crypto.randomUUID(),version=logoAssets.length+1,extension=input.mimeType==="image/png"?"png":input.mimeType==="image/jpeg"?"jpg":"webp";const asset:PropertyBrandAsset={id,propertyId,objectPath:`${tenantId}/${propertyId}/branding/${id}/logo-v${version}.${extension}`,publicUrl:input.dataUrl,mimeType:input.mimeType,byteSize:input.byteSize,version,isCurrent:true,retentionUntil:null};logoAssets.push(asset);record={...record,currentLogo:{...asset}};return structuredClone(asset)}
export function cleanupMockLogos(candidatePropertyId:string){if(candidatePropertyId!==propertyId)throw new Error("未找到当前酒店资料");const now=Date.now(),expired=logoAssets.filter(asset=>!asset.isCurrent&&asset.retentionUntil&&Date.parse(asset.retentionUntil)<=now);for(const asset of expired)logoAssets.splice(logoAssets.indexOf(asset),1);return expired.length}
