"use client";
import { useState } from "react";
import { DepartmentScopePicker } from "../hierarchy/DepartmentScopePicker";
import { Button } from "../ui/Button";
import { Dialog } from "../ui/Dialog";
import { RoleSwitcher } from "./RoleSwitcher";
import { usePrototypeFeedback } from "../../state/prototype-feedback";
import { usePathname } from "next/navigation";
const navigation=[{icon:"⌂",zh:"学习与发展总览",en:"Executive overview",href:"/"},{icon:"◇",zh:"组织培训看板",en:"Organization",href:"/organization"},{icon:"□",zh:"培训日历",en:"Training calendar",href:"/calendar"},{icon:"◌",zh:"课程成效",en:"Course effectiveness",href:"/effectiveness"},{icon:"△",zh:"风险看板",en:"Risk overview",href:"/risk"},{icon:"♙",zh:"员工中心",en:"People",href:"/people"},{icon:"◎",zh:"KPI 目标中心",en:"KPI targets",href:"/kpi"},{icon:"⌘",zh:"组织与权限",en:"Access",href:"/permissions"},{icon:"↥",zh:"导入中心",en:"Import",href:"/import"},{icon:"◈",zh:"酒店设置",en:"Hotel settings",href:"/settings/hotel"}];
export function AppShell({children}:{children:React.ReactNode}){const[createOpen,setCreateOpen]=useState(false);const[menuOpen,setMenuOpen]=useState(false);const{showToast}=usePrototypeFeedback();const pathname=usePathname();return <div className="app-shell">
  <aside className={`sidebar ${menuOpen?"open":""}`}><div className="brand brand-signature"><div className="brand-mark"><span>澜</span></div><div><strong>酒店学习与发展</strong><small>Hotel L&amp;D Operations</small></div></div><nav aria-label="主导航">{navigation.map((item,index)=><a className={`nav-item ${pathname===item.href?"active":""}`} href={item.href} key={item.zh} onClick={(e)=>{if(item.href.startsWith("#")){e.preventDefault();showToast(`${item.zh}将在下一检查点开放`)}}}><span>{item.icon}</span><div><strong>{item.zh}</strong><small>{item.en}</small></div>{index===4&&<em>3</em>}</a>)}</nav><div className="sidebar-foot"><div className="hotel-card"><span>SH</span><div><strong>上海澜庭酒店</strong><small>Shanghai Lanting Hotel</small></div></div></div></aside>
  <div className="main-column"><header className="topbar"><button className="mobile-menu" onClick={()=>setMenuOpen(!menuOpen)} aria-label="打开导航">☰</button><DepartmentScopePicker/><div className="control-cluster"><RoleSwitcher/><span className="control-divider"/><button className="round-button" onClick={()=>showToast("您目前没有新的系统通知")} aria-label="通知">♢<i/></button><button className="avatar" onClick={()=>showToast("账户菜单已打开：林静 · 超级管理员")}>林</button><Button className="primary create-button" onClick={()=>setCreateOpen(true)}><span>＋</span> 新建事项</Button></div></header><main>{children}</main></div>
  <Dialog open={createOpen} title="快速新建" onClose={()=>setCreateOpen(false)}><div className="quick-grid">{[["培训场次","Training session","07 / 18"],["培训分配","Training assignment","12 people"],["员工档案","Employee profile","New hire"],["补训计划","Make-up training","3 risks"]].map(([zh,en,note])=><button key={zh} onClick={()=>{setCreateOpen(false);showToast(`${zh}创建面板已准备`)}}><span>↗</span><strong>{zh}</strong><small>{en}</small><em>{note}</em></button>)}</div></Dialog>
  </div>}
