"use client";
import { AppShell } from "./components/shell/AppShell";
import { AppProviders } from "./providers";
import { useDepartmentScope } from "./state/department-scope";
import { usePrototypeFeedback } from "./state/prototype-feedback";

function FoundationPage(){const{breadcrumb}=useDepartmentScope();const{showToast}=usePrototypeFeedback();const current=breadcrumb.at(-1)!;return <AppShell><div className="page-wrap"><div className="page-intro"><div><span className="eyebrow">FRIDAY · 2026.07.11</span><h1>学习与发展总览</h1><p>Executive Learning &amp; Development Overview</p></div><div className="period-control"><button className="active">本月</button><button onClick={()=>showToast("季度视图将在仪表盘检查点开放")}>本季度</button><button onClick={()=>showToast("年度视图将在仪表盘检查点开放")}>本年度</button></div></div>
  <section className="insight-panel"><div className="insight-copy"><span className="eyebrow light">MANAGEMENT INSIGHT</span><h2>本月培训运营保持稳健，<br/><em>前厅部必修覆盖率</em>仍需优先关注。</h2><p>礼宾部有 3 名员工将在 7 天内逾期。建议安排补训，并向部门培训管理员发送提醒。</p><button onClick={()=>showToast("风险详情面板将在仪表盘检查点开放")}>查看管理建议 <span>→</span></button></div><div className="health-preview"><div className="health-ring"><span>86</span><small>健康分</small></div><div><strong>良好</strong><small>较上月 <em>+3.2</em></small></div></div></section>
  <div className="foundation-grid"><section className="foundation-card hierarchy-card"><div className="card-heading"><div><span className="eyebrow">SCOPE FOUNDATION</span><h3>组织范围</h3><p>Organization hierarchy</p></div><span className="status-pill"><i/> 已连接全部模块</span></div><div className="hierarchy-story"><div className="hierarchy-level"><span>01</span><button onClick={()=>showToast("已选择 Rooms 房务部")}>Rooms <small>房务部</small><em>32 人</em></button></div><div className="connector"/><div className="hierarchy-level indent"><span>02</span><button onClick={()=>showToast("已选择 Front Office 前厅部")}>Front Office <small>前厅部</small><em>18 人</em></button></div><div className="connector indent"/><div className="hierarchy-children"><button onClick={()=>showToast("已选择 Concierge 礼宾部")}>Concierge <small>礼宾部</small><em>6</em></button><button onClick={()=>showToast("已选择 Front Desk 前台")}>Front Desk <small>前台</small><em>8</em></button></div></div><div className="scope-summary"><span>当前范围</span><strong>{current.nameZh} {current.nameEn}</strong><small>{breadcrumb.map((item)=>item.nameZh).join(" / ")}</small></div></section>
  <section className="foundation-card"><div className="card-heading"><div><span className="eyebrow">TODAY'S FOCUS</span><h3>今日运营重点</h3><p>Operational priorities</p></div><button className="text-action" onClick={()=>showToast("优先事项列表已刷新")}>刷新 ↻</button></div><div className="priority-list">{[["01","消防安全补训","礼宾部 · 3 人","critical"],["02","新员工入职完成","前台 · 2 人","warning"],["03","课程反馈待回收","宴会部 · 8 份","normal"]].map(([n,title,meta,tone])=><button key={n} onClick={()=>showToast(`${title}详情已打开`)}><span className={tone}>{n}</span><div><strong>{title}</strong><small>{meta}</small></div><em>→</em></button>)}</div><button className="full-action" onClick={()=>showToast("已打开全部优先事项")}>查看全部运营事项 <span>→</span></button></section>
  </div><div className="foundation-note"><span>FOUNDATION CHECKPOINT</span><p>导航、组织层级、角色范围、交互反馈与视觉系统已建立。仪表盘数据组件将在您批准后进入下一检查点。</p></div></div></AppShell>}
export default function Home(){return <AppProviders><FoundationPage/></AppProviders>}
