"use client";
import { AppShell } from "./components/shell/AppShell";
import { AppProviders } from "./providers";
import { useDepartmentScope } from "./state/department-scope";
import { usePrototypeFeedback } from "./state/prototype-feedback";
const scopeProfiles:Record<string,{score:number;trend:number;people:number;coverage:number;risks:number;insight:string;kpis:number[];departments:[string,number,string][]}>={rooms:{score:86,trend:3.2,people:32,coverage:91.8,risks:3,insight:"前厅部必修覆盖是当前首要关注",kpis:[4.2,91.8,94,88.6],departments:[["前厅部",84,"3 项风险"],["客房部",91,"1 项风险"]]},"front-office":{score:82,trend:1.4,people:18,coverage:88.4,risks:3,insight:"礼宾部消防培训逾期需要本周处置",kpis:[3.8,88.4,91,86.2],departments:[["前台",88,"1 项风险"],["礼宾部",76,"2 项风险"],["宾客关系",91,"健康"]]},concierge:{score:76,trend:-2.1,people:6,coverage:78.5,risks:2,insight:"3 名员工必修培训临近或已经逾期",kpis:[3.1,78.5,83,80],departments:[["礼宾部",76,"2 项风险"]]}};
const definitions=[{name:"人均培训时数",unit:"小时",target:4},{name:"必修培训覆盖率",unit:"%",target:95},{name:"新员工完成率",unit:"%",target:92},{name:"计划完成率",unit:"%",target:90}];
function ExecutiveDashboard(){const{breadcrumb,departmentId}=useDepartmentScope();const{showToast}=usePrototypeFeedback();const current=breadcrumb.at(-1)!;const profile=scopeProfiles[departmentId]??scopeProfiles.rooms;const kpis=definitions.map((item,index)=>{const actual=profile.kpis[index];const completion=Math.round(actual/item.target*1000)/10;const gap=Math.round((actual-item.target)*10)/10;return{...item,actual,completion,gap,status:completion>=100?"healthy":completion>=90?"watch":"risk",statusLabel:completion>=100?"达标":completion>=90?"关注":"风险",trend:index===1?profile.trend:index%2?1.2:2.4}});return <AppShell><div className="page-wrap executive-cockpit"><div className="page-intro"><div><span className="date-line">2026 年 7 月 · {breadcrumb.map(d=>d.nameZh).join(" / ")}</span><h1>学习与发展运营总览</h1><p>Executive Learning &amp; Development Overview</p></div><div className="period-control"><button className="active">本月</button><button onClick={()=>showToast("已切换季度视图（原型）")}>本季度</button><button onClick={()=>showToast("已切换年度视图（原型）")}>本年度</button></div></div>
<section className="cockpit-hero"><div className="conclusion"><span>管理结论</span><h2>{current.nameZh}培训健康度为 {profile.score} 分，<br/><em>{profile.insight}</em>。</h2><p>当前范围覆盖 {profile.people} 名员工，较上月{profile.trend>=0?"提升":"下降"} {Math.abs(profile.trend)} 分。建议优先处理高风险必修培训，再跟进反馈回收。</p><button onClick={()=>showToast(`${current.nameZh}管理建议已展开`)}>查看管理建议 <b>→</b></button></div><div className="health-hero"><div className="health-orbit" style={{background:`conic-gradient(var(--champagne) 0 ${profile.score}%,rgba(191,161,106,.12) ${profile.score}%)`}}><div><strong>{profile.score}</strong><span>/ 100</span><small>培训健康分</small></div></div><div className="health-caption"><span><i/> {profile.score>=85?"运营状态良好":profile.score>=80?"需要关注":"存在风险"}</span><small>较上月 <em>{profile.trend>0?"+":""}{profile.trend}</em></small></div></div><div className="hero-trend"><div className="trend-head"><span>近 6 个月趋势</span><strong>{profile.trend>=0?"稳定向好":"需要干预"}</strong></div><div className="sparkline"><i style={{height:"38%"}}/><i style={{height:"48%"}}/><i style={{height:"45%"}}/><i style={{height:"61%"}}/><i style={{height:"70%"}}/><i className="active" style={{height:`${profile.score-8}%`}}/><span className="target-line">目标 85</span></div><div className="month-row"><span>2月</span><span>3月</span><span>4月</span><span>5月</span><span>6月</span><span>7月</span></div></div></section>
<div className="section-heading"><div><h3>KPI 目标完成</h3><p>Actual versus target · 本月</p></div><button onClick={()=>showToast("KPI 指标详情已打开")}>查看指标详情 →</button></div><section className="signal-grid">{kpis.map(kpi=><button className={`signal ${kpi.status}`} key={kpi.name} onClick={()=>showToast(`${kpi.name}详情已打开`)}><div className="signal-top"><span>{kpi.name}</span><em>{kpi.statusLabel}</em></div><div className="signal-value"><strong>{kpi.actual}</strong><small>{kpi.unit}</small></div><div className="kpi-contract"><span>实际值 <b>{kpi.actual}{kpi.unit}</b></span><span>目标值 <b>{kpi.target}{kpi.unit}</b></span><span>达成率 <b>{kpi.completion}%</b></span></div><div className="signal-track"><i style={{width:`${Math.min(kpi.completion,100)}%`}}/></div><div className="signal-foot"><span>目标差距 {kpi.gap>0?"+":""}{kpi.gap}{kpi.unit}</span><span>本月 · 较上月 {kpi.trend>=0?"↑":"↓"} {Math.abs(kpi.trend)}</span></div></button>)}</section>
<div className="dashboard-grid"><section className="tailored-card department-comparison"><div className="card-heading"><div><h3>部门表现对比</h3><p>Department comparison · 健康分与目标 85</p></div><button className="text-action" onClick={()=>showToast("部门对比详情已打开")}>查看详情</button></div><div className="comparison-list">{profile.departments.map(([name,score,risk])=><button key={name} onClick={()=>showToast(`${name}范围已准备切换`)}><div><strong>{name}</strong><small>{risk}</small></div><div className="comparison-track"><i style={{width:`${score}%`}}/><span style={{left:"85%"}}/></div><b>{score}</b></button>)}</div></section>
<section className="tailored-card effectiveness-list"><div className="card-heading"><div><h3>课程成效</h3><p>Course effectiveness · 满意度与反馈率</p></div><button className="text-action" onClick={()=>showToast("课程成效详情已打开")}>查看详情</button></div>{[["奢华服务沟通","4.8","92%"],["消防安全与应急响应","4.6","87%"],["宾客投诉处理","4.3","74%"]].map(([name,score,response],i)=><button className="course-row" key={name} onClick={()=>showToast(`${name}成效摘要已打开`)}><span>{i+1}</span><div><strong>{name}</strong><small>反馈回收 {response}</small></div><b>{score}<small>/5</small></b></button>)}</section>
<section className="tailored-card risk-ranking"><div className="card-heading"><div><h3>部门风险</h3><p>Risk ranking · 需要管理介入</p></div><span className="risk-count">{profile.risks} 项</span></div>{[["礼宾部","必修培训逾期","3 人","critical"],["前台","新员工进度低于目标","2 人","warning"],["宴会部","反馈回收率偏低","8 份","warning"]].slice(0,profile.risks).map(([dept,title,count,tone],i)=><button className="risk-row" key={title} onClick={()=>showToast(`${dept}风险处置已打开`)}><span>{i+1}</span><i className={tone}/><div><strong>{dept}</strong><small>{title}</small></div><b>{count}</b></button>)}</section>
<section className="tailored-card priority-panel"><div className="card-heading"><div><h3>行动优先级</h3><p>Action priorities · 本周</p></div><button className="text-action" onClick={()=>showToast("行动计划已刷新")}>刷新</button></div><div className="priority-callout"><span>01</span><div><strong>创建礼宾部消防安全补训</strong><small>建议完成时间：7 月 15 日前</small></div><button onClick={()=>showToast("补训创建面板已打开")}>立即处理 →</button></div><div className="mini-actions"><button onClick={()=>showToast("提醒发送面板已打开")}>发送必修提醒 <span>3 人</span></button><button onClick={()=>showToast("反馈跟进列表已打开")}>跟进课程反馈 <span>8 份</span></button></div></section></div></div></AppShell>}
export default function Home(){return <AppProviders><ExecutiveDashboard/></AppProviders>}
