"use client";
import { AppShell } from "./components/shell/AppShell";
import { AppProviders } from "./providers";
import { useDepartmentScope } from "./state/department-scope";
import { usePrototypeFeedback } from "./state/prototype-feedback";
function FoundationPage(){const{breadcrumb}=useDepartmentScope();const{showToast}=usePrototypeFeedback();const current=breadcrumb.at(-1)!;const signals=[["人均培训时数","4.2","小时","目标 4.0","105%","positive"],["必修培训覆盖率","91.8","%","目标 95%","96.6%","warning"],["新员工完成率","94.0","%","目标 92%","102%","positive"],["计划完成率","88.6","%","目标 90%","98.4%","neutral"]];return <AppShell><div className="page-wrap executive-cockpit"><div className="page-intro"><div><span className="date-line">2026 年 7 月 · 上海澜庭酒店</span><h1>学习与发展运营总览</h1><p>Executive Learning &amp; Development Overview</p></div><div className="period-control"><button className="active">本月</button><button onClick={()=>showToast("季度视图将在仪表盘检查点开放")}>本季度</button><button onClick={()=>showToast("年度视图将在仪表盘检查点开放")}>本年度</button></div></div>
  <section className="cockpit-hero"><div className="conclusion"><span>管理结论</span><h2>本月培训健康度保持稳健，<br/><em>前厅部必修覆盖</em>是当前首要关注。</h2><p>整体绩效较上月提升 3.2 分。礼宾部 3 名员工将在 7 天内逾期，建议优先安排本周补训。</p><button onClick={()=>showToast("管理建议已展开")}>查看管理建议 <b>→</b></button></div><div className="health-hero"><div className="health-orbit"><div><strong>86</strong><span>/ 100</span><small>培训健康分</small></div></div><div className="health-caption"><span><i/> 运营状态良好</span><small>较上月 <em>+3.2</em></small></div></div><div className="hero-trend"><div className="trend-head"><span>近 6 个月趋势</span><strong>稳定向好</strong></div><div className="sparkline"><i style={{height:"38%"}}/><i style={{height:"48%"}}/><i style={{height:"45%"}}/><i style={{height:"61%"}}/><i style={{height:"70%"}}/><i className="active" style={{height:"82%"}}/><span className="target-line">目标 85</span></div><div className="month-row"><span>2月</span><span>3月</span><span>4月</span><span>5月</span><span>6月</span><span>7月</span></div></div></section>
  <div className="section-heading"><div><h3>关键运营信号</h3><p>Key operational signals</p></div><button onClick={()=>showToast("指标详情将在仪表盘检查点开放")}>查看指标详情 →</button></div><section className="signal-grid">{signals.map(([name,value,unit,target,completion,tone])=><button className={`signal ${tone}`} key={name} onClick={()=>showToast(`${name}详情已打开`)}><div className="signal-top"><span>{name}</span><em>{completion} 达成</em></div><div className="signal-value"><strong>{value}</strong><small>{unit}</small></div><div className="signal-track"><i style={{width:`${Math.min(Number(completion.replace("%","")),100)}%`}}/></div><div className="signal-foot"><span>{target}</span><span>较上月 ↑</span></div></button>)}</section>
  <div className="lower-grid"><section className="tailored-card scope-compact"><div className="card-heading"><div><h3>组织范围</h3><p>Organization scope</p></div><span className="status-pill"><i/> 全部模块同步</span></div><div className="crumb-line">{breadcrumb.map((item,index)=><span key={item.id}>{index>0&&<b>›</b>}{item.nameZh} <small>{item.nameEn}</small></span>)}</div><div className="scope-current"><div><span>当前范围</span><strong>{current.nameZh}</strong><small>{current.nameEn}</small></div><div className="scope-mini-metrics"><span><strong>32</strong><small>员工</small></span><span><strong>91.8%</strong><small>必修覆盖</small></span><span><strong>3</strong><small>风险</small></span></div></div><div className="department-chips"><button onClick={()=>showToast("已选择前厅部")}>前厅部 <small>Front Office</small><em>18</em></button><button onClick={()=>showToast("已选择客房部")}>客房部 <small>Housekeeping</small><em>14</em></button></div></section>
  <section className="tailored-card action-card"><div className="card-heading"><div><h3>优先行动</h3><p>Priority actions</p></div><button className="text-action" onClick={()=>showToast("优先行动已刷新")}>刷新</button></div><div className="action-list">{[["critical","消防安全补训","礼宾部 · 3 人 · 7 天内逾期"],["warning","新员工培训跟进","前台 · 2 人 · 完成度低于目标"],["positive","反馈回收提醒","宴会部 · 8 份待回收"]].map(([tone,title,meta])=><button key={title} onClick={()=>showToast(`${title}已打开`)}><i className={tone}/><div><strong>{title}</strong><small>{meta}</small></div><span>→</span></button>)}</div></section></div></div></AppShell>}
export default function Home(){return <AppProviders><FoundationPage/></AppProviders>}
