import { resolveRequestId } from "../../../lib/neon/request-id.ts";
import { OrganizationApiError, organizationErrorResponse, runAuthorizedNeonOrganizationOperationalUnitRead, runAuthorizedNeonOrganizationOperationalUnitWrite } from "../../../services/neon-organization-authorization.ts";

export async function GET(request: Request) { const requestId=resolveRequestId(request); try { noQuery(request); const result=await runAuthorizedNeonOrganizationOperationalUnitRead(request,requestId,(repository,propertyId)=>repository.listOperationalUnits(propertyId)); return Response.json(result.data,{headers:result.headers}); } catch(error) { return organizationErrorResponse(error,requestId); } }
export async function POST(request: Request) { const requestId=resolveRequestId(request); try { noQuery(request); const input=createInput(await body(request)); const result=await runAuthorizedNeonOrganizationOperationalUnitWrite(request,requestId,(repository,propertyId)=>repository.createOperationalUnit({...input,propertyId})); return Response.json(result.data,{status:201,headers:result.headers}); } catch(error) { return organizationErrorResponse(error,requestId); } }
function noQuery(request:Request){if([...new URL(request.url).searchParams.keys()].length)throw new OrganizationApiError(400,"运营单元请求不接受查询参数");}
async function body(request:Request){try{return await request.json();}catch{throw new OrganizationApiError(400,"运营单元请求格式无效");}}
function createInput(value:unknown){const row=record(value); only(row,["tenantId","departmentId","parentOperationalUnitId","unitType","code","nameZh","nameEn","sortOrder"]); return {tenantId:uuid(row.tenantId,"租户标识无效"),propertyId:"",departmentId:uuid(row.departmentId,"部门标识无效"),parentOperationalUnitId:nullableUuid(row.parentOperationalUnitId,"父运营单元标识无效"),unitType:type(row.unitType),code:string(row.code,"编码无效"),nameZh:string(row.nameZh,"中文名称无效"),nameEn:string(row.nameEn,"英文名称无效"),sortOrder:int(row.sortOrder,"排序值无效")};}
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i; function record(v:unknown){if(!v||typeof v!=="object"||Array.isArray(v))throw new OrganizationApiError(400,"运营单元请求格式无效");return v as Record<string,unknown>;} function only(row:Record<string,unknown>,keys:string[]){if(!Object.keys(row).every(k=>keys.includes(k)))throw new OrganizationApiError(400,"运营单元请求包含不支持的字段");} function uuid(v:unknown,m:string){if(typeof v!=="string"||!UUID.test(v))throw new OrganizationApiError(400,m);return v.toLowerCase();} function nullableUuid(v:unknown,m:string){if(v===null)return null;return uuid(v,m);} function string(v:unknown,m:string){if(typeof v!=="string")throw new OrganizationApiError(400,m);return v;} function int(v:unknown,m:string){if(typeof v!=="number"||!Number.isSafeInteger(v))throw new OrganizationApiError(400,m);return v;} function type(v:unknown){if(!["venue","outlet","kitchen","restaurant","recreation","other"].includes(String(v)))throw new OrganizationApiError(400,"运营单元类型无效");return v as "venue"|"outlet"|"kitchen"|"restaurant"|"recreation"|"other";}
